if select(2,UnitClass("player")) ~= "SHAMAN" then return end
local L = LibStub("AceLocale-3.0"):NewLocale("TotemTimers", "enUS", true, true)

if L then

L["Air Button"] = true
L["Cooldown"] = true
L["Ctrl-Leftclick to remove weapon buffs"] = true
L["Delete Set"] = "Delete Totem Set %u?"
L["Earth Button"] = true
L["Fire Button"] = true
L["Leftclick to cast %s"] = true
L["Leftclick to cast spell"] = true
L["Leftclick to load totem set"] = true
L["Leftclick to open totem set menu"] = true
L["Long Cooldown"] = true
L["Maelstrom Notifier"] = "Maelstrom ready!"
L["Middleclick to cast %s"] = true
L["Next leftclick casts %s"] = true
L["Reset"] = "TotemTimers has been reset!"
L["Rightclick to assign both %s and %s to leftclick"] = true
L["Rightclick to assign spell to leftclick"] = true
L["Rightclick to assign totem to timer button"] = true
L["Rightclick to cast %s"] = true
L["Rightclick to delete totem set"] = true
L["Rightclick to save active totem configuration as set"] = true
L["Shield removed"] = "%s removed"
L["Shift-Rightclick to assign spell to middleclick"] = true
L["Shift-Rightclick to assign spell to rightclick"] = true
L["Totem Destroyed"] = "%s has been destroyed."
L["Totem Expired"] = "%s has expired"
L["Totem Expiring"] = "%s about to expire"
L["Water Button"] = true


--GUI

L = LibStub("AceLocale-3.0"):NewLocale("TotemTimers_GUI", "enUS", true, true)

L["Air"] = true
L["Automatic"] = true
L["Bottom"] = true
L["Cast Button 1"] = true
L["Cast Button 2"] = true
L["Clickthrough"] = true
L["Clickthrough Desc"] = "Disables any clicking functionality of the timer buttons"
L["Crowd Control"] = true
L["Down"] = true
L["Earth"] = true
L["Enable"] = true
L["Fire"] = true
L["Flame Shock Duration"] = true
L["Flame Shock Duration Desc"] = "Show Flame Shock Duration for Elemental"
L["Flame Shock Duration Restoration"] = "Flame Shock for Restoration"
L["Flame Shock Duration Restoration Desc"] = "Show Flame Shock Duration for Restoration"
L["Left"] = true
L["Maelstrom Bar"] = true
L["Maelstrom Bar Desc"] = "Show Maelstrom Bar for Enhancement and Elemental"
L["Mana Bar"] = true
L["Mana Bar Desc"] = "Show Mana Bar for Restoration"
L["none"] = true
L["Right"] = true
L["Top"] = true
L["Totems"] = true
L["TotemTimers"] = true
L["Up"] = true
L["Version"] = true
L["vertical"] = true
L["Water"] = true

L["Blizz Style"] = true
L["Color Timer Bars"] = true
L["Color Timer Bars according to their elements."] = true
L["Debug"] = true
L["Displays timer bars underneath times"] = true
L["Fulmination Aura"] = true
L["Fulmination Aura Desc"] = "Shows an aura around your character if Lightning Shield stacks get to 9 as Ele using WoW's built-in PowerAuras"
L["Fulmination Glow"] = true
L["Fulmination Glow Desc"] = "Lets the Earth Shock cooldown timer and action bar buttons containing Earth Shock glow if Lightning Shield gets to 9 stacks"
L["General"] = true
L["Hide Blizzard Timers"] = true
L["Hide Default Totem Bar"] = true
L["Hide Default Totem Bar Desc"] = "If you uncheck this you should reload your interface."
L["Hide In Vehicles"] = true
L["Hide In Vehicles Desc"] = "Hides TotemTimers while driving a vehicle. Do not change this setting while driving"
L["Lock"] = true
L["Locks the position of TotemTimers"] = true
L["RaidTotems"] = true
L["RaidTotems Desc"] = "Sets the multicast spell to which totems send by the RaidTotems addon are assigned."
L["Red Flash Color"] = true
L["RedFlash Desc"] = "If enabled expiring timers flash red, else they will fade in and out."
L["Reset All"] = true
L["Reset Positions"] = true
L["Show Key Bindings"] = true
L["Shows key bindings on totem timers"] = true
L["Shows tooltips on timer and totem buttons"] = true
L["Show Timer Bars"] = true
L["Show Tooltips"] = true
L["Stop Pulse"] = true
L["Stop Pulse Desc"] = " \"If a timer stops its icon gives a big visible pulse\""
L["Time Color"] = true
L["Time Font"] = true
L["Timer Bar Color"] = true
L["Timer Bar Texture"] = true
L["Timers On Buttons"] = true
L["Tooltips At Buttons"] = true
L["Tooltips At Buttons Desc"] = "Shows Tooltips to the right of TT's buttons."

L["Advanced Options"] = true
L["Always Visible Desc"] = "Totem menus are always visible and can be dragged around like action bars."
L["Arrangement"] = true
L["Basic layout of the four timer buttons, loose lets you move them individually"] = true
L["box"] = true
L["Button Size"] = true
L["Cast Button Position"] = true
L["Cast Button Position Desc"] = "Sets the position of the additional customizable totem buttons next to the totem timers"
L["Cast Button Size"] = true
L["Cast Button Size Desc"] = "Sets the size of the addition customizable totem buttons relative to the size of the totem timers"
L["Enable Pulse Bar"] = true
L["Enables the four totem timer buttons and menus"] = true
L["horizontal"] = true
L["Keybindings desc"] = "If enabled, totem buttons will have mapped the keys 1-9 to them if totem menus are shown|nYou have to relog for this setting to take effect."
L["loose"] = true
L["Mini Icons Desc"] = "Shows the small icons in the lower right of the timer buttons which indicate the totem assigned to the active multicast spell and the timer  button will cast."
L["Open On Rightclick"] = true
L["Player Range"] = true
L["Player Range Desc"] = "Shows a red dot on a totem timer if player is out of range"
L["Pulse desc"] = "Shows a green status bar inside the timers that fills until a totem pulses."
L["Raid Member Range"] = true
L["Raid Range Tooltip"] = true
L["Range Desc"] = "Shows how many raid members do not get the buff of your totem in the lower left corner"
L["Reverse Key Bindings"] = true
L["Reverse Key Desc"] = "Bind keys in order 9-1 instead of 1-9|nYou have to relog for this setting to take effect."
L["Rightclick Desc"] = "Open the totem menus on a rightclick instead of hovering over the timer button. Totems can then be dismissed with the middle mouse button instead of a rightclick."
L["RR Tooltip Desc"] = "Shows a list of raid members not in range of your totem on mouseover"
L["Scales the timer buttons"] = true
L["Scaling"] = true
L["Sets the font size of time strings"] = true
L["Sets the format in which times are displayed"] = true
L["Sets the space between timer buttons"] = true
L["Sets the space between timer buttons and timer bars"] = true
L["Sets the width of timer bars."] = true
L["Show Mini Icons"] = true
L["Show Totem Cooldowns"] = true
L["Spacing"] = true
L["Timer Bar Position"] = true
L["Timer Bar Position Desc"] = "Sets at which side of the timer icons the times are displayed"
L["Timer Bar Width"] = true
L["Timer Bar Width Desc"] = "Sets the width of the timer bars."
L["Timer Button 1"] = true
L["Timer Button 2"] = true
L["Timer Button 3"] = true
L["Timer Button 4"] = true
L["Timers"] = true
L["Timers On Buttons Desc"] = "Timers are displayed on the buttons instead of next to them. If enabled, the weapon tracker will only show the time for the main hand weapon when dual wielding."
L["Time Size"] = true
L["Time Spacing"] = true
L["Time Style"] = true
L["Totem Cooldowns desc"] = "Shows cooldowns of all totems with longer cooldowns as additional timer bars."
L["Totem menu direction"] = true
L["Totem menu direction desc"] = "Sets the direction in which the totem menus open. Automatic determines the direction based on the timer's position."
L["Totem Menu Key Bindings"] = true
L["Totem Menus Always Visible"] = true
L["Totem Menu Spacing"] = true
L["Totem Menu Spacing Desc"] = "Sets the spacing of buttons in the totem menus. Only applies if menus are always visible."

L["Ankh Tracker"] = true
L["Ankh Tracker Desc"] = "Shows the remaining cooldown of your reincarnation ability as well as the number of ankhs in your bags. Also is used to save and load totem sets."
L["Button 4"] = true
L["EarthShieldDesc"] = "Shows the remaining Earth Shield time and charges. Can be used to cast Earth Shield."
L["EarthShieldOptionsDesc"] = "If 'recast' is selected as option for a mouse button, the shield is cast on the last person it was cast out of combat or the person assigned by the RaidTotems addon. Default Usage: Target you ES target and cast the spell on it by rightclicking the button out of combat. Then you can target somebody else, but the ES will still be cast on the same person by leftclicking, even in combat."
L["Earth Shield Tracker"] = true
L["ES Charges only"] = "Charges only"
L["ES Charges only desc"] = "Disables the time display and shows ES charges in its place|nChanges take effect the next time you cast ES"
L["ES Main Tank Desc"] = "On mouseover shows a menu containing up to 4 main tanks of your raid/party"
L["ES Main Tank menu"] = "Main Tank menu"
L["esrecast"] = "recast (last target/RaidTotems)"
L["Leftclick"] = true
L["Middle Button"] = true
L["Rightclick"] = true
L["Shield Tracker"] = true
L["Trackers"] = true
L["Weapon Buff Tracker"] = true
L["WeaponDesc"] = "Shows the remaining time of your weapon buffs. Leftclick cast the selected weapon buff, rightclick opens a menu to select a buff. I an icon shows two buffs, the first leftclick cast the left buff and a second leftclick the right buff."

L["Color"] = true
L["disabled warnings desc"] = "Even if a tracker is disabled, its warnings of expired buffs will still be shown"
L["EarthShield warnings"] = true
L["Maelstrom notification"] = true
L["Messages"] = true
L["Shield expiration warnings"] = true
L["Show warnings of disabled trackers"] = true
L["Sound"] = true
L["Totem Desctruction Desc"] = "Warning if a totem is destroyed before it is expired."
L["Totem Destruction Message"] = true
L["Totem Expiration Desc"] = "Warning after a totem expires."
L["Totem Expiration Message"] = true
L["Totem Expiration Warning"] = true
L["Totem Warning Desc"] = "Warns 10 secs before a totem expires."
L["Warnings"] = true
L["Weapon buff warnings"] = true

L["Cooldowns"] = true
L["Duration"] = true
L["ECD Button Size"] = true
L["ECD Font Size"] = true
L["EnhanceCDs"] = true
L["Flame Shock on top"] = true
L["Flame Shock on top desc"] = "Shows Flame Shock duration and Maelstrom bar above cooldowns"
L["Hide OOC Desc"] = "Changing this setting will have effect after the next combat"
L["Hide out of combat"] = true
L["Lava Surge Aura"] = true
L["Lava Surge Aura Desc"] = "Shows an aura around your character if Lava Surge procs using WoW's built-in PowerAuras"
L["Lava Surge Glow"] = true
L["Lava Surge Glow Desc"] = "Lets the Lava Burst cooldown timer and action bar buttons containing Lava Burst glow if Lava Surge procs"
L["Long Cooldowns"] = true
L["Maelstrom Bar Height"] = true
L["OOC Alpha"] = true
L["OOC Alpha Desc"] = "Controls the opacity of the buttons out of combat, 0 = transparent, 1 = opaque"
L["Show OmniCC counters"] = true
L["Spells"] = true

L["Arena"] = true
L["Battleground"] = true
L["Copy All"] = true
L["Copy CC Settings"] = true
L["Copy EnhanceCDs Settings"] = true
L["Copy Frame Positions"] = true
L["Copy From"] = true
L["Copy General Settings"] = true
L["Copy Settings"] = true
L["Copy To"] = true
L["Copy Totem Settings"] = true
L["Copy Totem Timer Settings"] = true
L["Copy Tracker Settings"] = true
L["Copy Warnings"] = true
L["Create Profile"] = true
L["default"] = "Default"
L["Delete Profile"] = true
L["Manage Profiles"] = true
L["New Name"] = true
L["Party"] = true
L["Profile"] = true
L["Profile already exists."] = true
L["Profiles"] = true
L["Raid"] = true
L["Really delete profile?"] = true
L["Really reset frame positions?"] = true
L["Reset Frame Positions"] = true
L["Reset Profile"] = true
L["Select Profiles"] = true
L["Solo"] = true
L["You cannot delete the default profile."] = true
L["You need to enter a profile name first."] = true

end

-- de_DE

L = LibStub("AceLocale-3.0"):NewLocale("TotemTimers", "deDE")

if L then

L["Air Button"] = "Luftbutton"
L["Cooldown"] = "Abklingzeit"
L["Ctrl-Leftclick to remove weapon buffs"] = "Strg-Linksklick um Waffenbuffs zu entfernen"
L["Delete Set"] = "Totemset %u löschen?"
L["Earth Button"] = "Erdbutton"
L["Fire Button"] = "Feuerbutton"
L["Leftclick to cast %s"] = "Linksklick um %s zu zaubern"
L["Leftclick to cast spell"] = "Linksklick um Spruch zu zaubern"
L["Leftclick to load totem set"] = "Linksklick um Totemset zu laden"
L["Leftclick to open totem set menu"] = "Linksklick um Totemsetmenü zu öffnen"
L["Long Cooldown"] = "Lange Abklingzeit"
L["Maelstrom Notifier"] = "Mahlstrom bereit!"
L["Middleclick to cast %s"] = "Mittelklick um %s zu zaubern"
L["Next leftclick casts %s"] = "Nächster Linksklick zaubert %s"
L["Reset"] = "TotemTimers wurde zurückgesetzt!"
L["Rightclick to assign both %s and %s to leftclick"] = "Rechtsklick um %s und %s Linksklick zuzuweisen"
L["Rightclick to assign spell to leftclick"] = "Rechtsklick um Zauber Linksklick zuzuweisen"
L["Rightclick to assign totem to timer button"] = "Rechtsklick um Totem dem Timerknopf zuzuweisen"
L["Rightclick to cast %s"] = "Rechtsklick um %s zu zaubern"
L["Rightclick to delete totem set"] = "Rechtsklick um Totemset zu löschen"
L["Rightclick to save active totem configuration as set"] = "Rechtsklick um Totemkonfiguration als Set zu speichern"
L["Shield removed"] = "%s entfernt"
L["Shift-Rightclick to assign spell to middleclick"] = "Shift-Rechtsklick um Zauber Mittelklick zuzuweisen"
L["Shift-Rightclick to assign spell to rightclick"] = "Shift-Rechtsklick um Zauber Rechtsklick zuzuweisen"
L["Totem Destroyed"] = "%s ist zerstört."
L["Totem Expired"] = "%s ist ausgelaufen"
L["Totem Expiring"] = "%s läuft aus"
L["Water Button"] = "Wasserbutton"

end

L = LibStub("AceLocale-3.0"):NewLocale("TotemTimers_GUI", "deDE")
if L then

L["Air"] = "Luft"
L["Automatic"] = "Automatisch"
L["Bottom"] = "Unten"
L["Cast Button 1"] = "Totembutton 1"
L["Cast Button 2"] = "Totembutton 2"
L["Clickthrough"] = true
L["Clickthrough Desc"] = "Ignoriert Mausklicks auf den Timerbuttons"
L["Crowd Control"] = true
L["Down"] = "Runter"
L["Earth"] = "Erde"
L["Enable"] = "Aktivieren"
L["Fire"] = "Feuer"
L["Flame Shock Duration"] = "Flammenshock-Dauer"
L["Flame Shock Duration Desc"] = "Zeigt die Dauer des Flammenshock-Debuffs auf dem aktuellen Ziel an"
L["Flame Shock Duration Restoration"] = "Flammenshock für Wiederherstellung"
L["Flame Shock Duration Restoration Desc"] = "Zeigt den Flammenschock-Debuff für Wiederherstellung an"
L["Left"] = "Links"
L["Maelstrom Bar"] = "Malstromleiste"
L["Maelstrom Bar Desc"] = "Zeigt Malstrom für Verstärker und Elementar an"
L["Mana Bar"] = "Manaleiste"
L["Mana Bar Desc"] = "Zeigt Mana für Wiederherstellung an"
L["none"] = "Keinen"
L["Right"] = "Rechts"
L["Top"] = "Oben"
L["Totems"] = true
L["TotemTimers"] = true
L["Up"] = "Hoch"
L["Version"] = true
L["vertical"] = "vertikal"
L["Water"] = "Wasser"

L["Blizz Style"] = "Allgemein"
L["Color Timer Bars"] = "Timerleisten einfärben"
L["Color Timer Bars according to their elements."] = "Die Timerleisten der 4 Totemtimer werden passend zu ihren Elementen eingefärbt."
L["Debug"] = true
L["Displays timer bars underneath times"] = "Zeigt graphische Leisten unterhalb der Zeitanzeigen"
L["Fulmination Aura"] = "Entladungsaura"
L["Fulmination Aura Desc"] = "Zeigt eine Aura über eurem Charakter, wenn die Aufladungen eures Blitzschlagschilds 9 erreichen."
L["Fulmination Glow"] = "Entladungsleuchten"
L["Fulmination Glow Desc"] = "Der Erdschockcooldown und entsprechende Knöpfe auf den Aktionsleisten leuchten, wenn die Aufladungen eures Blitzschlagschilds 9 erreichen. "
L["General"] = "Allgemein"
L["Hide Blizzard Timers"] = "Blizzards Timer ausschalten"
L["Hide Default Totem Bar"] = "Standardtotembar ausschalten"
L["Hide Default Totem Bar Desc"] = "Wenn du dies änderst, solltest du dein Interface neu laden."
L["Hide In Vehicles"] = "In Fahrzeugen ausblenden"
L["Hide In Vehicles Desc"] = "In Fahrzeugen (Belagerungsmaschinen etc.) wird das TT-Interface ausgeblendet"
L["Lock"] = "Fixieren"
L["Locks the position of TotemTimers"] = "Fixiert die Position aller Buttons"
L["RaidTotems"] = true
L["RaidTotems Desc"] = "Legt den Zauber fest, dem die vom RaidTotems-Addon gesendeten Totems zugewiesen werden."
L["Red Flash Color"] = "Rotes Leuchten"
L["RedFlash Desc"] = "Timer blinken in rot, kurz bevor sie enden, ansonsten blinken sie durchsichtig."
L["Reset All"] = "Alles zurücksetzen"
L["Reset Positions"] = "Positionen zurücksetzen"
L["Show Key Bindings"] = "Zeige Tastenbelegung"
L["Shows key bindings on totem timers"] = "Zeigt die Tastenbelegung auf Timern an"
L["Shows tooltips on timer and totem buttons"] = "Tooltips werden angezeigt, sobald du mit der Maus über einen Timer oder Totem fährst."
L["Show Timer Bars"] = "Timerleisten anzeigen"
L["Show Tooltips"] = "Tooltips anzeigen"
L["Stop Pulse"] = true
L["Stop Pulse Desc"] = "Ein ausgelaufener Timer pulsiert kurz aber sehr auffällig"
L["Time Color"] = "Zeitfarbe"
L["Time Font"] = "Zeit-Schriftart"
L["Timer Bar Color"] = "Timerleisten-Farbe"
L["Timer Bar Texture"] = "Timerleisten-Textur"
L["Timers On Buttons"] = "Timer auf Buttons"
L["Tooltips At Buttons"] = "Tooltips an Knöpfen"
L["Tooltips At Buttons Desc"] = "Zeigt die Tooltips rechts an den Knöpfen von TT an."

L["Advanced Options"] = "Erweiterte Optionen"
L["Always Visible Desc"] = "Die Totemmenüs werden dauerhaft angezeigt und können wie Aktionsleiten plaziert werden."
L["Arrangement"] = "Anordnung"
L["Basic layout of the four timer buttons, loose lets you move them individually"] = "Anordnung der 4 Totemtimer in einer Reihe, als Box oder einzeln verschiebbar."
L["box"] = true
L["Button Size"] = "Buttongröße"
L["Cast Button Position"] = "Timer"
L["Cast Button Position Desc"] = "Legt die Position für die totemabhängigen Buttons neben den 4 Timern fest"
L["Cast Button Size"] = "CastButton-Größe"
L["Cast Button Size Desc"] = "Legt die Größe der totemabhängigen Buttons neben den 4 Timern fest."
L["Enable Pulse Bar"] = "Procleiste"
L["Enables the four totem timer buttons and menus"] = "Schaltet die vier Totemtimer und die Totemmenüs ein"
L["horizontal"] = true
L["Keybindings desc"] = "Die Totems in den Menüs können bei Anzeige mit den Tasten 1-9 gestellt werden|nWird erst nach dem nächsten Login übernommen."
L["loose"] = "beliebig"
L["Mini Icons Desc"] = "Zeigt kleine Icons unten rechts in den Totemtimern an, die angeben, welches Totem bei Klick auf den Timer gestellt wird."
L["Open On Rightclick"] = "Mit Rechtsklick öffnen"
L["Player Range"] = "Spielerreichweite"
L["Player Range Desc"] = "Zeigt einen roten Punkt auf einem Timer, wenn du außerhalb der Reichweite deines Totems bist"
L["Pulse desc"] = "Zeigt einen grünen Balken innerhalb eines Timers an, der voll ist, sobald das Totem seinen Effekt auslöst."
L["Raid Member Range"] = "Raidreichweite"
L["Raid Range Tooltip"] = "Reichweitentooltip"
L["Range Desc"] = "Zeigt, wieviele Spieler nicht in der Reichweite deines Totems sind"
L["Reverse Key Bindings"] = "Totemnummerierung umkehren"
L["Reverse Key Desc"] = "Die Totems in den Menüs werden von 9-1 nummeriert anstatt von 1-9.|nWird erst nach dem nächsten Login übernommen."
L["Rightclick Desc"] = "Die Totemmenüs öffnen sich über einen Rechtsklick. Totems werden dann durch den mittleren Mausknopf statt den rechten zerstört."
L["RR Tooltip Desc"] = "Zeigt eine Liste der Spieler außerhalb der Reichweite der Totems an, wenn du mit der Maus über einen Timer fährst."
L["Scales the timer buttons"] = "Skaliert die Timerbuttons"
L["Scaling"] = "Skalierung"
L["Sets the font size of time strings"] = "Skaliert die Schriftgröße der Zeitanzeige"
L["Sets the format in which times are displayed"] = "Stellt das Format für die Zeitanzeige ein"
L["Sets the space between timer buttons"] = "Skaliert den Abstand zwischen den Timern"
L["Sets the space between timer buttons and timer bars"] = "Skaliert den Abstand zwischen Button und Zeit"
L["Sets the width of timer bars."] = "Skaliert die Breite der Timerleisten"
L["Show Mini Icons"] = "MiniIcons anzeigen"
L["Show Totem Cooldowns"] = "Zeige Totemcooldowns"
L["Spacing"] = "Abstand"
L["Timer Bar Position"] = "Zeit-Position"
L["Timer Bar Position Desc"] = "Gibt die Seite der Buttons an, an denen die Timer angzeigt werden"
L["Timer Bar Width"] = "Timerleistenbreite"
L["Timer Bar Width Desc"] = "Stellt die Breit der Timer ein"
L["Timer Button 1"] = "Timer 1"
L["Timer Button 2"] = "Timer 2"
L["Timer Button 3"] = "Timer 3"
L["Timer Button 4"] = "Timer 4"
L["Timers"] = "Timer"
L["Timers On Buttons Desc"] = "Die Timer werden auf den Buttons angezeigt anstelle in separaten Leisten"
L["Time Size"] = "Schriftgröße"
L["Time Spacing"] = "Zeitabstand"
L["Time Style"] = "Zeitanzeige"
L["Totem Cooldowns desc"] = "Zeigt die Cooldowns von allen Totems mit längeren CDs auf zusätzlichen Timerleisten."
L["Totem menu direction"] = "Totemmenürichtung"
L["Totem menu direction desc"] = "Stellt die Richtung ein, in der sich die Totemmenüs öffnen"
L["Totem Menu Key Bindings"] = "Tastenbelegung für Totems"
L["Totem Menus Always Visible"] = "Totemmenüs ständig geöffnet"
L["Totem Menu Spacing"] = "Totemmenüabstand"
L["Totem Menu Spacing Desc"] = "Skaliert den Abstand der Knöpfe in den Totemmenüs zueinander. Hat nur einen Effekt, wenn die Menüs dauerhaft angzeiegt werden."

L["Ankh Tracker"] = "Wiederbelebungstimer"
L["Ankh Tracker Desc"] = "Zeigt die verbleibende Zeit des Cooldowns von Wiederbelebung (Ankh) an"
L["Button 4"] = "Mausknopf 4"
L["EarthShieldDesc"] = "Zeigt die verbleibenden Aufladungen deines Erdschilds an und kann dazu benutzt werden, dein Erdschild neu zu zaubern."
L["EarthShieldOptionsDesc"] = "Wenn 'Letztes Ziel' ausgewählt wurde für einen Mausknopf, zaubert ein Klick mit dem entsprechenden Knopf das Erdschild auf die Person, die es zuletzt außerhalb des Kampfes erhalten hat. (Standardbenutzung: Visiere dein Erdschildziel an und zauberes es mit einem Rechtsklick außerhalb des Kampfes, danach kannst du dein Ziel wechseln und dieselbe Person bekomm das Erdschild trotzdem mit einem Linksklick, auch im Kampf."
L["Earth Shield Tracker"] = "Erdschild-Tracker"
L["ES Charges only"] = "Nur Aufladungen"
L["ES Charges only desc"] = "Entfernt die Timeranzeige und zeigt die ES-Aufladungen an ihrer Stelle|nÄnderungen werden erst mit dem nächsten Erdschild übernommen"
L["ES Main Tank Desc"] = "Zeigt ein Menü mit bis zu 4 Maintanks deiner Gruppe"
L["ES Main Tank menu"] = "Maintankmenü"
L["esrecast"] = "Letztes Ziel/RaidTotems"
L["Leftclick"] = "Linksklick"
L["Middle Button"] = "Mittlerer Knopf"
L["Rightclick"] = "Rechtsklick"
L["Shield Tracker"] = "Schild-Tracker"
L["Trackers"] = "Tracker"
L["Weapon Buff Tracker"] = "Waffenbuff-Tracker"
L["WeaponDesc"] = "Zeigt die verbleibende Zeit deiner Waffenbuffs an. Ein Rechtsklick öffnet ein Menü mit den vorhandenen Waffenbuffs, ein weiterer Rechtsklick auf einen Waffenbuff selektiert diesen. Danach kann der Buff mit einem Linksklick auf den Waffenbuff-Tracker gezaubert werden."

L["Color"] = "Farbe"
L["disabled warnings desc"] = "Auch wenn ein Tracker deaktiviert wurde, wird vor dem Auslaufen des zugehörigen Zaubers gewarnt"
L["EarthShield warnings"] = "Erdschildauslauf"
L["Maelstrom notification"] = "5 Mahlstrom-Stacks"
L["Messages"] = "Warnungen"
L["Shield expiration warnings"] = "Schildauslauf"
L["Show warnings of disabled trackers"] = "Deaktivierte Tracker warnen trotzdem"
L["Sound"] = true
L["Totem Desctruction Desc"] = "Warnt, wenn ein Totem vor Ablauf zerstört wurde."
L["Totem Destruction Message"] = "Totem zerstört."
L["Totem Expiration Desc"] = "Warnt, wenn ein Totem abläuft."
L["Totem Expiration Message"] = "Bei Totemablauf"
L["Totem Expiration Warning"] = "Vor Totemauslauf"
L["Totem Warning Desc"] = "Warnt 10 Sekunden, bevor ein Totem abläuft."
L["Warnings"] = "Warnungen"
L["Weapon buff warnings"] = "Waffenbuffauslauf"

L["Cooldowns"] = "Abklingzeiten"
L["Duration"] = "Dauer"
L["ECD Button Size"] = "VCD-Größe"
L["ECD Font Size"] = "VCD-Schriftgröße"
L["EnhanceCDs"] = "Verstärker CDs"
L["Flame Shock on top"] = "Flammenschock oben"
L["Flame Shock on top desc"] = "Flammenschockdauer wird überhalb der Cooldowns angezeigt"
L["Hide OOC Desc"] = "Wird erst nach dem nächsten Kampf geändert"
L["Hide out of combat"] = "Verstecke außerhalb des Kampfes"
L["Lava Surge Aura"] = "Lavasog-Aura"
L["Lava Surge Aura Desc"] = "Zeigt eine Aura um deinen Character wenn Lavasog auslöst mittels des in WoW eingebauten PowerAuras"
L["Lava Surge Glow"] = "Lavasog-Leuchten"
L["Lava Surge Glow Desc"] = "Lässt den Cooldown von Lavaeruption sowie entsprechende Knöpfe auf den Aktionsleisten leuchten wenn Lavasog auslöst"
L["Long Cooldowns"] = "Lange Abklingzeiten"
L["Maelstrom Bar Height"] = "Mahlstromleistenhöhe"
L["OOC Alpha"] = "OOC-Transparenz"
L["OOC Alpha Desc"] = "Steuert die Transparenz der Knöpfe außerhalb des Kampfs, 0 = transparent, 1 = undurchsichtig"
L["Show OmniCC counters"] = "OmniCC-Timer"
L["Spells"] = "Zauber"

L["Arena"] = true
L["Battleground"] = "Schlachtfeld"
L["Copy All"] = "Kopiere Alles"
L["Copy CC Settings"] = "Kopiere CC"
L["Copy EnhanceCDs Settings"] = "Kopiere EnhanceCDs"
L["Copy Frame Positions"] = "Kopiere Positionen"
L["Copy From"] = "Kopiere von"
L["Copy General Settings"] = "Kopiere Allgemeine Einstellungen"
L["Copy Settings"] = "Einstellungen kopieren"
L["Copy To"] = "Kopiere nach"
L["Copy Totem Settings"] = "Kopiere Totemeinstellungen"
L["Copy Totem Timer Settings"] = "Kopiere Totemtimer-Einstellungen "
L["Copy Tracker Settings"] = "Kopiere Trackereinstellungen"
L["Copy Warnings"] = "Warnungen kopieren"
L["Create Profile"] = "Profil erstellen"
L["default"] = "Standard"
L["Delete Profile"] = "Profil löschen"
L["Manage Profiles"] = "Profile verwalten"
L["New Name"] = "Neuer Profilname"
L["Party"] = "Gruppe"
L["Profile"] = "Profil"
L["Profile already exists."] = "Profil existiert bereits."
L["Profiles"] = "Profile"
L["Raid"] = "Schlachtzug"
L["Really delete profile?"] = "Profil wirklich löschen?"
L["Really reset frame positions?"] = "Positionen wirklich zurücksetzen?"
L["Reset Frame Positions"] = "Positionen zurücksetzen"
L["Reset Profile"] = "Profil zurücksetzen"
L["Select Profiles"] = "Profile auswählen"
L["Solo"] = true
L["You cannot delete the default profile."] = "Das Standardprofil kann nicht gelöscht werden."
L["You need to enter a profile name first."] = "Du musst zuerst einen Profilnamen eingeben."

end



local L = LibStub("AceLocale-3.0"):NewLocale("TotemTimers", "frFR")
if L then
L["Air Button"] = "bouton Totem de l'air"
L["Cooldown"] = "Recharge" -- Needs review
L["Ctrl-Leftclick to remove weapon buffs"] = "Ctrl-clic gauche pour supprimer les améliorations d'armes"
L["Delete Set"] = "Supprimer l'ensemble des Totem %u?"
L["Earth Button"] = "bouton Totem de la Terre"
L["Fire Button"] = "Bouton feu"
L["Leftclick to cast %s"] = "Clic gauche pour lancer %s"
L["Leftclick to cast spell"] = "Clic gauche pour lancer les sorts"
L["Leftclick to load totem set"] = "Clic gauche pour charger le set de vos totems sur %s" -- Needs review
L["Leftclick to open totem set menu"] = "Clic gauche pour ouvrir votre set de totem"
L["Long Cooldown"] = "Recharge longue" -- Needs review
L["Maelstrom Notifier"] = "Maelstrom ready!"
L["Middleclick to cast %s"] = "Clic milieu pour lancer %s"
L["Next leftclick casts %s"] = "Clic gauche suivant lance %s"
L["Reset"] = "Bouton efface"
L["Rightclick to assign both %s and %s to leftclick"] = "Faites un clic droit pour assigner à la fois %s et %s au clic gauche"
L["Rightclick to assign spell to leftclick"] = "Clic droit pour assigner le sort au clic gauche"
L["Rightclick to assign totem to timer button"] = "Rightclick to assign totem to timer button" -- Requires localization
L["Rightclick to cast %s"] = "Clic droit pour lancer %s"
L["Rightclick to delete totem set"] = "Clic droit pour supprimer votre set de Totem"
L["Rightclick to save active totem configuration as set"] = "Clic droit pour enregistrer la configuration de vos totems actifs"
L["Shield removed"] = "%s enlevé"
L["Shift-Rightclick to assign spell to middleclick"] = "Maj-clic droit pour assigner le sort au clic du milieu"
L["Shift-Rightclick to assign spell to rightclick"] = "Maj-clic droit pour assigner le sort au clic droit"
L["Totem Destroyed"] = "%s a été détruit"
L["Totem Expired"] = "%s a expiré"
L["Totem Expiring"] = "%s va expirer"
L["Water Button"] = "bouton Totem de l'eau"
end


local L = LibStub("AceLocale-3.0"):NewLocale("TotemTimers_GUI", "frFR")
if L then

L["Air"] = "Air "
L["Automatic"] = "Automatique"
L["Bottom"] = "Bas"
L["Cast Button 1"] = "Bouton 1 de lancer"
L["Cast Button 2"] = "Bouton 2 de lancer"
L["Clickthrough"] = "Clic option"
L["Clickthrough Desc"] = "Désactive toutes les fonctionnalités en cliquant sur les boutons de la minuterie"
L["Crowd Control"] = "Contrôle" -- Needs review
L["Down"] = "Bas"
L["Earth"] = "Terre"
L["Enable"] = "Activer"
L["Fire"] = "Feu"
L["Flame Shock Duration"] = "Flame Shock Duration" -- Requires localization
L["Flame Shock Duration Desc"] = "Show Flame Shock Duration for Elemental" -- Requires localization
L["Flame Shock Duration Restoration"] = "Flame Shock for Restoration" -- Requires localization
L["Flame Shock Duration Restoration Desc"] = "Show Flame Shock Duration for Restoration" -- Requires localization
L["Left"] = "Gauche"
L["Maelstrom Bar"] = "Maelstrom Bar" -- Requires localization
L["Maelstrom Bar Desc"] = "Show Maelstrom Bar for Enhancement and Elemental" -- Requires localization
L["Mana Bar"] = "Mana Bar" -- Requires localization
L["Mana Bar Desc"] = "Show Mana Bar for Restoration" -- Requires localization
L["none"] = "Aucun"
L["Right"] = "Doite"
L["Top"] = "Haut"
L["Totems"] = true
L["TotemTimers"] = true
L["Up"] = "Au-dessus"
L["Version"] = true
L["vertical"] = true
L["Water"] = "Eau"

L["Blizz Style"] = true
L["Color Timer Bars"] = "Couleur de la barre"
L["Color Timer Bars according to their elements."] = "Couleur de la barre du minuteur en fonction de leurs éléments."
L["Debug"] = true
L["Displays timer bars underneath times"] = "Affiche un fond de |cff9932CCcouleur|r derrière le timer |n(Qui se trouve au dessus de votre barre de totem)"
L["Fulmination Aura"] = "Aura Invectives"
L["Fulmination Aura Desc"] = "Affiche une aura autour de votre personnage " -- Needs review
L["Fulmination Glow"] = "Invectives lueur"
L["Fulmination Glow Desc"] = "Lets the Earth Shock cooldown timer and action bar buttons containing Earth Shock glow if Lightning Shield gets to 9 stacks" -- Requires localization
L["General"] = "Général"
L["Hide Blizzard Timers"] = "Cache le timer de Blizzard"
L["Hide Default Totem Bar"] = "Cache par défaut la Barre de Totem"
L["Hide Default Totem Bar Desc"] = "Si vous décochez cela, vous devez recharger votre interface."
L["Hide In Vehicles"] = "Cacher dans les véhicules"
L["Hide In Vehicles Desc"] = "Cache TotemTimers en conduite d'un véhicule. Ne changez pas ce réglage pendant la conduite"
L["Lock"] = "Verrouille"
L["Locks the position of TotemTimers"] = "Verrouille les barres de|n        |cffff4488Totem|r|cff1E90FFTimer|r"
L["RaidTotems"] = true
L["RaidTotems Desc"] = "Définit ici, l'Appel des totems aux quelles il envoi l'assigne par l'addon RaidTotems."
L["Red Flash Color"] = "Flash |cffFF0000Rouge|r"
L["RedFlash Desc"] = "|cff7fff7fSi elle est activée:|r |nLorsque le timer prend fin, |nclignotement |cffFF0000Rouge|r  |nsinon juste un fondu"
L["Reset All"] = "Reset tout"
L["Reset Positions"] = true
L["Show Key Bindings"] = "Affiche les raccourcis clavier"
L["Shows key bindings on totem timers"] = "Affiche la touche en raccourcis clavier sur |cffff4488Totem|r|cff1E90FFTimer|r"
L["Shows tooltips on timer and totem buttons"] = "Affiche une info-bulle sur les boutons de selection du totem"
L["Show Timer Bars"] = "Affiche la barre du Timer"
L["Show Tooltips"] = "Affiche les info-bulles"
L["Stop Pulse"] = "Stop battement"
L["Stop Pulse Desc"] = "\"Si la minuterie s'arrête, l'icône donne un plus gros battement\""
L["Time Color"] = "Couleur du Timer"
L["Time Font"] = "Police du Timer"
L["Timer Bar Color"] = "Minuterie couleur de la barre "
L["Timer Bar Texture"] = "Texture de la barre."
L["Timers On Buttons"] = "Timer sur les boutons"
L["Tooltips At Buttons"] = "Boutons des info-bulles"
L["Tooltips At Buttons Desc"] = "Affiche les info-bulles à la droite des boutons de TT."

L["Advanced Options"] = "Options avancées"
L["Always Visible Desc"] = "La barre des totem peut être affichés en permanence et peuvent être positionnés comme des barres d'action."
L["Arrangement"] = "Direction"
L["Basic layout of the four timer buttons, loose lets you move them individually"] = "Structure de base des quatre boutons de la minuterie, vous pouvez les déplacer individuellement"
L["box"] = "case"
L["Button Size"] = "Taille du bouton"
L["Cast Button Position"] = "Position du bouton pour lancer"
L["Cast Button Position Desc"] = "Définit la position des boutons personnalisables à côté du Timer"
L["Cast Button Size"] = "Taille du bouton de lancer"
L["Cast Button Size Desc"] = "Définit la taille de l'ajout des boutons personnalisables en rapport à la taille des compteurs de durée du totem"
L["Enable Pulse Bar"] = "Activer le battement de la Barre"
L["Enables the four totem timer buttons and menus"] = "Active les quatre boutons des totem et leurs menus"
L["horizontal"] = true
L["Keybindings desc"] = "|cff7fff7fSi elle est activée:|r |n les boutons des totem seront réparties sur les touches 1-9 si les menus sont affichés |nVous devez reconnecter pour que ce paramètre prenne effet."
L["loose"] = "détacher"
L["Mini Icons Desc"] = "Affiche des petites icônes en bas à droite du Totem, qui précisera quel totem prendra le relais."
L["Open On Rightclick"] = "Clic droit pour Ouvrir"
L["Player Range"] = "Joueur distan"
L["Player Range Desc"] = "Montre un point rouge sur sur le Timer du totem si le joueur est hors de portée"
L["Pulse desc"] = "Affiche une barre verte au coeur du timer et qui se remplit dès que le totem déclenche son effet."
L["Raid Member Range"] = "Distance des membres du raid"
L["Raid Range Tooltip"] = "Distance du raid - infobulle "
L["Range Desc"] = "Montre combien des membres du raid ne reçoivent pas le buff de vos totem dans le coin en bas à gauche"
L["Reverse Key Bindings"] = "Inverser les raccourcis clavier"
L["Reverse Key Desc"] = "Les totem sont numérotés 9-1 au lieu de 1-9.|n Vous devez reconnecter pour que ce paramètre prenne effet."
L["Rightclick Desc"] = "Ouvrir le menu des totem en faisant un clic droit au lieu de survoler au-dessus des boutons. Les totem peuvent ensuite être détruis avec le bouton central de la souris au lieu d'un clic droit."
L["RR Tooltip Desc"] = "Affiche une liste des joueurs hors de portée des totem, si vous survolez avec votre souris"
L["Scales the timer buttons"] = "Bascule sur le bouton TIMER"
L["Scaling"] = "Escalade"
L["Sets the font size of time strings"] = "Définit la taille de police et de la durée d'affichage"
L["Sets the format in which times are displayed"] = "Définit le format dans lequel les heures sont indiquées"
L["Sets the space between timer buttons"] = "Définit l'espace entre les boutons du Timer"
L["Sets the space between timer buttons and timer bars"] = "Définit l'espace entre les boutons et la barre du Timer"
L["Sets the width of timer bars."] = "Définit la largeur des barres du Timer."
L["Show Mini Icons"] = "affiche les mini icônes"
L["Show Totem Cooldowns"] = "Affiche les recharges"
L["Spacing"] = "Espacement"
L["Timer Bar Position"] = "Timer barre de position"
L["Timer Bar Position Desc"] = "Fixe de quel côté l'icône du timer s'affiche et le temps"
L["Timer Bar Width"] = "Timer largeur des barres"
L["Timer Bar Width Desc"] = "Définit la largeur des barres deu timer."
L["Timer Button 1"] = "Timer Bouton 1"
L["Timer Button 2"] = "Timer Bouton 2"
L["Timer Button 3"] = "Timer Bouton 3"
L["Timer Button 4"] = "Timer Bouton 4"
L["Timers"] = true
L["Timers On Buttons Desc"] = "Les minutes sont affichés sur les boutons au lieu d'à côté. Si elle est activée, le traqueur d'arme ne fera que montrer le temps de l'arme en main droite lors de l'ambidextrie."
L["Time Size"] = "Time taille"
L["Time Spacing"] = "Time espacement"
L["Time Style"] = true
L["Totem Cooldowns desc"] = "Affiche le temps de recharge de tous les totem sur d'autres CD avec des barres de timer plus long."
L["Totem menu direction"] = true
L["Totem menu direction desc"] = "Définit la direction dans laquelle les menus du totem s'ouvre. Détermine automatiquement la direction en fonction de la position du Timer"
L["Totem Menu Key Bindings"] = "Raccourcis clavier"
L["Totem Menus Always Visible"] = "Barre des totem visible"
L["Totem Menu Spacing"] = "Totem menu espacement"
L["Totem Menu Spacing Desc"] = "Définit l'espacement des boutons dans les menus du totem. Ne s'applique que si les menus sont toujours visibles."

L["Ankh Tracker"] = "Ankh "
L["Ankh Tracker Desc"] = "Affiche le temps de recharge de la capacité restante de votre réincarnation, ainsi que le nombre de ankhs dans vos sacs. Est également utilisé pour enregistrer et charger les jeux de totem."
L["Button 4"] = "Bouton 4"
L["EarthShieldDesc"] = "Affiche le temps restant de votre bouclier de terre et les charges. Peut être utilisé pour lancer Bouclier de terre."
L["EarthShieldOptionsDesc"] = "Si 'relance' est sélectionné comme option par un bouton de la souris, le bouclier est jeté sur la dernière personne qui fut hors de combat ou de la personne affectée par l'addon Raidtotem. Utilisation par défaut: Sélection de votre cible pour le BT et lancer le sort avec le bouton droit. Ensuite, vous pouvez cibler quelqu'un d'autre, mais le BT sera encore lancé sur la même personne bouton gauche, même combat."
L["Earth Shield Tracker"] = "Bouclier de terre"
L["ES Charges only"] = "charge seulement"
L["ES Charges only desc"] = "Disables the time display and shows ES charges in its place|nChanges take effect the next time you cast ES" -- Requires localization
L["ES Main Tank Desc"] = "Au passage de la souris affiche un menu contenant jusqu'à 4 main tank de votre raid /groupe"
L["ES Main Tank menu"] = "Main Tank menu"
L["esrecast"] = "relance (dernière cible / Raidtotem)"
L["Leftclick"] = "Clic gauche"
L["Middle Button"] = "Bouton du milieu"
L["Rightclick"] = "Clicdroit"
L["Shield Tracker"] = "Bouclier"
L["Trackers"] = "Traqueur"
L["Weapon Buff Tracker"] = "Buff des armes"
L["WeaponDesc"] = "Indique le temps restant de votre améliorations d'armes. Clic gauche lance le buffs sur l'arme sélectionnée, clic droit ouvre un menu pour sélectionner un Buff. Une icône montre deux Buffs, le clic gauche lance le premier Buffs à gauche et un deuxième clic gauche pour le Buffs de droite."

L["Color"] = "Couleur"
L["disabled warnings desc"] = "Même si un traqueur est désactivé, ses avertissements de buffs expiré sera toujours affiché"
L["EarthShield warnings"] = "Bouclier de terre Avertissements"
L["Maelstrom notification"] = "Maelstrom annonce"
L["Messages"] = true
L["Shield expiration warnings"] = "Bouclier signal d'expiration"
L["Show warnings of disabled trackers"] = "Affiche les avertissements du Traqueur"
L["Sound"] = "Son"
L["Totem Desctruction Desc"] = "Signale si un totem est détruit avant qu'il ne soit expiré."
L["Totem Destruction Message"] = "Totem détruits."
L["Totem Expiration Desc"] = "Avertit si un totem expire."
L["Totem Expiration Message"] = "Totem expiration du message"
L["Totem Expiration Warning"] = "Totem expiration de l'alerte"
L["Totem Warning Desc"] = "Avertit 10 secondes avant l'expiration d'un totem."
L["Warnings"] = "Alerte"
L["Weapon buff warnings"] = "Buff arme alerte"

L["Cooldowns"] = "Recharges" -- Needs review
L["Duration"] = "Durée"
L["ECD Button Size"] = "Taille du bouton de recharge"
L["ECD Font Size"] = "Taille de la police de la recharge"
L["EnhanceCDs"] = "Mise en valeur du CD"
L["Flame Shock on top"] = "Horion de flammes au-dessus" -- Needs review
L["Flame Shock on top desc"] = "Affiche la durée de Horion de flammes et la barre du Maelstrom ci-dessus avec les temps de recharge"
L["Hide OOC Desc"] = "Modifier ce paramètre prendra effet après le prochain combat"
L["Hide out of combat"] = "Masquer hors de combat"
L["Lava Surge Aura"] = "Aura Vague de lave"
L["Lava Surge Aura Desc"] = "Affiche une aura autour de votre personnage si Lava Surge procs à l'aide de PowerAuras intégré à WoW"
L["Lava Surge Glow"] = "Lueur Vague de lave"
L["Lava Surge Glow Desc"] = "Lets the Lava Burst cooldown timer and action bar buttons containing Lava Burst glow if Lava Surge procs" -- Requires localization
L["Long Cooldowns"] = "Temps de recharge longs" -- Needs review
L["Maelstrom Bar Height"] = "Maelstrom hauteur de la barre"
L["OOC Alpha"] = "Opacité"
L["OOC Alpha Desc"] = "Contrôles de l'opacité des boutons hors de combat, 0 = transparent, 1= opaque|n|n|cffFFF8DCTraduction:|r |n|cff1E90FFVî|r |cffF0FFFFb|r |cff8B0000ë|r |cffFFF8DCserveur|r |cff7FFF00Dalaran|r |n"
L["Show OmniCC counters"] = "Active OmniCC (addon)"
L["Spells"] = "Sorts" -- Needs review

L["Arena"] = "Arène" -- Needs review
L["Battleground"] = "Champ de bataille" -- Needs review
L["Copy All"] = "Tout copier" -- Needs review
L["Copy CC Settings"] = "Copie des paramètres" -- Needs review
L["Copy EnhanceCDs Settings"] = "Copy EnhanceCDs Settings" -- Requires localization
L["Copy Frame Positions"] = "Copier la position de vos cadres" -- Needs review
L["Copy From"] = "Copier à partir de" -- Needs review
L["Copy General Settings"] = "Copie des paramètres généraux" -- Needs review
L["Copy Settings"] = "Paramètres de copie" -- Needs review
L["Copy To"] = "Pour copier" -- Needs review
L["Copy Totem Settings"] = "Copier les réglages de vos totems" -- Needs review
L["Copy Totem Timer Settings"] = "Copier les paramètres du timer de vos totems" -- Needs review
L["Copy Tracker Settings"] = "Copier les paramètres du Tracker" -- Needs review
L["Copy Warnings"] = "Avertissements de la copie" -- Needs review
L["Create Profile"] = "Créer un profil" -- Needs review
L["default"] = "défaut" -- Needs review
L["Delete Profile"] = "Supprimer le profil" -- Needs review
L["Manage Profiles"] = "Gérer les profils" -- Needs review
L["New Name"] = "Nouveau nom" -- Needs review
L["Party"] = "Party" -- Requires localization
L["Profile"] = true -- Needs review
L["Profile already exists."] = "Le Profil existe déjà." -- Needs review
L["Profiles"] = true -- Needs review
L["Raid"] = true -- Needs review
L["Really delete profile?"] = "Voulez-vous vraiment supprimer le profil?" -- Needs review
L["Really reset frame positions?"] = "Voulez-vous vraiment faire un nouveau réglage des positions de cadre ?" -- Needs review
L["Reset Frame Positions"] = "Réinitialiser la position des cadres" -- Needs review
L["Reset Profile"] = "Réinitialiser le profil" -- Needs review
L["Select Profiles"] = "Sélection du profil" -- Needs review
L["Solo"] = true -- Needs review
L["You cannot delete the default profile."] = "Vous ne pouvez pas supprimer le profil par défaut." -- Needs review
L["You need to enter a profile name first."] = "Vous devez entrer un nom de profil en premier." -- Needs review

end


L = LibStub("AceLocale-3.0"):NewLocale("TotemTimers", "esES")
if L then
L["Air Button"] = "Air Button" -- Requires localization
L["Cooldown"] = "Cooldown" -- Requires localization
L["Ctrl-Leftclick to remove weapon buffs"] = "Pulsa Control-Click izquierdo para eliminar las ventajas del arma"
L["Delete Set"] = "Delete Totem Set %u?" -- Requires localization
L["Earth Button"] = "Earth Button" -- Requires localization
L["Fire Button"] = "Fire Button" -- Requires localization
L["Leftclick to cast %s"] = "Pulsa Click izquierdo para lanzar %s"
L["Leftclick to cast spell"] = "Pulsa Click izquierdo para lanzar el hechizo"
L["Leftclick to load totem set"] = "Leftclick to load totem set" -- Requires localization
L["Leftclick to open totem set menu"] = "Leftclick to open totem set menu" -- Requires localization
L["Long Cooldown"] = "Long Cooldown" -- Requires localization
L["Maelstrom Notifier"] = "Maelstrom ready!" -- Requires localization
L["Middleclick to cast %s"] = "Boton central para lanzar %s"
L["Next leftclick casts %s"] = "Siguiente Click izquierdo lanzara %s" -- Needs review
L["Reset"] = "Reinicio de TotemTimers!"
L["Rightclick to assign both %s and %s to leftclick"] = "Pulsa Click izquierdo para asignar %s y %s al click derecho"
L["Rightclick to assign spell to leftclick"] = "Pulsa Click derecho para asignar el hechizo a click izquierdo"
L["Rightclick to assign totem to timer button"] = "Rightclick to assign totem to timer button" -- Requires localization
L["Rightclick to cast %s"] = "Pulsa Click derecho para lanzar %s"
L["Rightclick to delete totem set"] = "Rightclick to delete totem set" -- Requires localization
L["Rightclick to save active totem configuration as set"] = "Rightclick to save active totem configuration as set" -- Requires localization
L["Shield removed"] = "%s removed" -- Requires localization
L["Shift-Rightclick to assign spell to middleclick"] = "Pulsa Shift-Click Derecho para asignar un hechizo al click central"
L["Shift-Rightclick to assign spell to rightclick"] = "Pulsa Shift-Click Derecho para asignar el hechizo a click derecho"
L["Totem Destroyed"] = "%s es destruido"
L["Totem Expired"] = "%s has expired" -- Requires localization
L["Totem Expiring"] = "%s se esta acabando"
L["Water Button"] = "Water Button" -- Requires localization

end


L = LibStub("AceLocale-3.0"):NewLocale("TotemTimers", "zhCN")
if L then
L["Air Button"] = "空气图腾"
L["Cooldown"] = "冷却"
L["Ctrl-Leftclick to remove weapon buffs"] = "Ctrl-左键点击删除武器增益"
L["Delete Set"] = "删除图腾设置 %u?"
L["Earth Button"] = "大地图腾"
L["Fire Button"] = "火焰图腾"
L["Leftclick to cast %s"] = "左键点击施放 %s"
L["Leftclick to cast spell"] = "左键点击施放法术"
L["Leftclick to load totem set"] = "左键点击加载图腾设置 %s"
L["Leftclick to open totem set menu"] = "左键打开设置界面"
L["Long Cooldown"] = "长时间冷却"
L["Maelstrom Notifier"] = "漩涡武器就绪!"
L["Middleclick to cast %s"] = "中键点击施放 %s"
L["Next leftclick casts %s"] = "下一个左键点击施放 %s"
L["Reset"] = "重置图腾计时器!"
L["Rightclick to assign both %s and %s to leftclick"] = "和 %s 和 %s 都到左键点击"
L["Rightclick to assign spell to leftclick"] = "右键点击指定法术到左键点击"
L["Rightclick to assign totem to timer button"] = "右键点击指定图腾到计时器."
L["Rightclick to cast %s"] = "右键点击施放 %s"
L["Rightclick to delete totem set"] = "右键删除图腾设置"
L["Rightclick to save active totem configuration as set"] = "右键保存激活的图腾设置"
L["Shield removed"] = "%s 效果消失"
L["Shift-Rightclick to assign spell to middleclick"] = "Shift-右键点击分配法术到中键点击"
L["Shift-Rightclick to assign spell to rightclick"] = "Shift-右键点击分配法术到右键点击"
L["Totem Destroyed"] = "%s 被摧毁了"
L["Totem Expired"] = "%s 到期了"
L["Totem Expiring"] = "%s 即将到期"
L["Water Button"] = "水之图腾"
end

L = LibStub("AceLocale-3.0"):NewLocale("TotemTimers_GUI", "zhCN")
if L then

L["Air"] = "空气图腾"
L["Automatic"] = "自动"
L["Bottom"] = "底部"
L["Cast Button 1"] = "施法按钮1"
L["Cast Button 2"] = "施法按钮2"
L["Clickthrough"] = "点击"
L["Clickthrough Desc"] = "禁用任何点击功能的定时器按钮"
L["Crowd Control"] = "控制技能"
L["Down"] = "向下"
L["Earth"] = "大地图腾"
L["Enable"] = "启用"
L["Fire"] = "火焰图腾"
L["Flame Shock Duration"] = "Flame Shock Duration" -- Requires localization
L["Flame Shock Duration Desc"] = "Show Flame Shock Duration for Elemental" -- Requires localization
L["Flame Shock Duration Restoration"] = "Flame Shock for Restoration" -- Requires localization
L["Flame Shock Duration Restoration Desc"] = "Show Flame Shock Duration for Restoration" -- Requires localization
L["Left"] = "左侧"
L["Maelstrom Bar"] = "Maelstrom Bar" -- Requires localization
L["Maelstrom Bar Desc"] = "Show Maelstrom Bar for Enhancement and Elemental" -- Requires localization
L["Mana Bar"] = "Mana Bar" -- Requires localization
L["Mana Bar Desc"] = "Show Mana Bar for Restoration" -- Requires localization
L["none"] = "无"
L["Right"] = "右侧"
L["Top"] = "顶部"
L["Totems"] = "图腾设置"
L["TotemTimers"] = "图腾计时器"
L["Up"] = "向上"
L["Version"] = "版本"
L["vertical"] = "垂直排列"
L["Water"] = "水之图腾"

L["Blizz Style"] = "暴雪样式"
L["Color Timer Bars"] = "着色计时条"
L["Color Timer Bars according to their elements."] = "根据元素计时条上色."
L["Debug"] = "调试"
L["Displays timer bars underneath times"] = "显示计时条在时间下方"
L["Fulmination Aura"] = "撼天雷电光环"
L["Fulmination Aura Desc"] = "如果使用魔兽世界内置的 PowerAuras 并且闪电盾堆叠到9层时则显示了一个光环围绕你的角色"
L["Fulmination Glow"] = "撼天雷电光环"
L["Fulmination Glow Desc"] = "如果闪电盾堆叠到9层时,让大地震击冷却计时器与动作列按钮显示大地震击辉光"
L["General"] = "综合"
L["Hide Blizzard Timers"] = "隐藏暴雪计时器"
L["Hide Default Totem Bar"] = "隐藏默认的图腾条"
L["Hide Default Totem Bar Desc"] = "如果你取消这个你应该重新载入你的界面."
L["Hide In Vehicles"] = "在载具中时隐藏"
L["Hide In Vehicles Desc"] = "当在载具中时隐藏 TotemTimers. 在驾驶时请不要改动此设置"
L["Lock"] = "锁定"
L["Locks the position of TotemTimers"] = "锁定 TotemTimers 的位置"
L["RaidTotems"] = "团队图腾"
L["RaidTotems Desc"] = "设置图腾组法术根据团队图腾插件发送的图腾来分配."
L["Red Flash Color"] = "红光闪烁"
L["RedFlash Desc"] = "如果启用到期时间红光闪烁,否则淡入或淡出."
L["Reset All"] = "重置全部"
L["Reset Positions"] = "重置位置"
L["Show Key Bindings"] = "显示快捷键"
L["Shows key bindings on totem timers"] = "在图腾计时上显示快捷键"
L["Shows tooltips on timer and totem buttons"] = "在计时跟图腾按钮上显示提示"
L["Show Timer Bars"] = "在时间下方显示计时条"
L["Show Tooltips"] = "显示提示信息"
L["Stop Pulse"] = "停止脉冲"
L["Stop Pulse Desc"] = " \"如果一个计时器停止其图标会出现一个可见的大脉冲效果\""
L["Time Color"] = "时间颜色"
L["Time Font"] = "时间字体"
L["Timer Bar Color"] = "计时条颜色"
L["Timer Bar Texture"] = "计时条材质"
L["Timers On Buttons"] = "按钮上显示时间"
L["Tooltips At Buttons"] = "显示提示信息"
L["Tooltips At Buttons Desc"] = "在图腾按钮的右侧显示提示信息."

L["Advanced Options"] = "进阶设置"
L["Always Visible Desc"] = "图腾选单总是可见像动作条一样四处拖动."
L["Arrangement"] = "排列方式"
L["Basic layout of the four timer buttons, loose lets you move them individually"] = "4个计时按钮的基本样式, 自由排列让你单独移动"
L["box"] = "方格排列"
L["Button Size"] = "按钮大小"
L["Cast Button Position"] = "施法按钮位置"
L["Cast Button Position Desc"] = "设置图腾额外自订的按钮位置与旁边的图腾计时"
L["Cast Button Size"] = "施法按钮大小"
L["Cast Button Size Desc"] = "设置图腾额外自订的按钮大小与旁边的图腾计时关联大小"
L["Enable Pulse Bar"] = "启用脉动条"
L["Enables the four totem timer buttons and menus"] = "启用4个图腾计时器按钮和菜单"
L["horizontal"] = "水平排列"
L["Keybindings desc"] = "如果启用, 如果图腾选单显示图腾按钮将会有按键1-9|n你必须重登设置才会生效."
L["loose"] = "自由排列"
L["Mini Icons Desc"] = "在标示图腾分配的计时按钮右下显示小图示来启动多施法法术和计时按钮将会施放."
L["Open On Rightclick"] = "鼠标右键点击打开选单"
L["Player Range"] = "玩家距离提示"
L["Player Range Desc"] = "如果玩家超出距离时在图腾计时器上显示一个红点"
L["Pulse desc"] = "在计时里面显示绿色状态条直到充满图腾脉动."
L["Raid Member Range"] = "团队成员距离提示"
L["Raid Range Tooltip"] = "显示团队成员距离列表"
L["Range Desc"] = "在左下角显示有多少团队成员没有获得你的图腾增益"
L["Reverse Key Bindings"] = "反转图腾选单快捷键"
L["Reverse Key Desc"] = "锁定按键9-1而不是1-9|n你必须重登这个设置才会生效."
L["Rightclick Desc"] = "右键开启图腾选单而不是经过计时按钮. 用滑鼠中键按钮可以图腾解散而不是右键点击."
L["RR Tooltip Desc"] = "滑鼠经过时显示团队成员清单没有在你图腾范围内"
L["Scales the timer buttons"] = "缩放图腾按钮"
L["Scaling"] = "縮放"
L["Sets the font size of time strings"] = "设置计时字串的字型大小"
L["Sets the format in which times are displayed"] = "设置按钮之间的间隔"
L["Sets the space between timer buttons"] = "设置按钮之间的间隔"
L["Sets the space between timer buttons and timer bars"] = "设置按钮和计时条之间的间隔"
L["Sets the width of timer bars."] = "设置计时条的宽度."
L["Show Mini Icons"] = "显示小图标"
L["Show Totem Cooldowns"] = "显示图腾冷却"
L["Spacing"] = "图标间距"
L["Timer Bar Position"] = "计时条位置"
L["Timer Bar Position Desc"] = "设置在哪一方的图示计时器显示的时间"
L["Timer Bar Width"] = "计时条宽度"
L["Timer Bar Width Desc"] = "设置计时条宽度."
L["Timer Button 1"] = "计时按钮1"
L["Timer Button 2"] = "计时按钮2"
L["Timer Button 3"] = "计时按钮3"
L["Timer Button 4"] = "计时按钮4"
L["Timers"] = "按钮设置"
L["Timers On Buttons Desc"] = "计时显示在按钮上而不是在他们旁边. 如果启用, 武器追踪只会显示时间当双持时只有主手武器."
L["Time Size"] = "字体大小"
L["Time Spacing"] = "计时条与图标间距"
L["Time Style"] = "时间格式"
L["Totem Cooldowns desc"] = "所有图腾显示冷却就像额外的计时条不再冷却."
L["Totem menu direction"] = "图腾选单方向"
L["Totem menu direction desc"] = "设置图腾选单开启方向. 自动确定方向基于计时的位置."
L["Totem Menu Key Bindings"] = "显示图腾选单快捷键"
L["Totem Menus Always Visible"] = "图腾选单总是显示"
L["Totem Menu Spacing"] = "图腾选单内图标间隔"
L["Totem Menu Spacing Desc"] = "在图腾选单设置按钮间隔. 只允许如果选单总是可见."

L["Ankh Tracker"] = "复生"
L["Ankh Tracker Desc"] = "显示复生技能的剩余冷却时间以及你的背包内十字章的数量. 也可以用来保存和加载图腾设置."
L["Button 4"] = "鼠标按钮4点击"
L["EarthShieldDesc"] = "显示大地之盾的剩余时间和次数. 可以用来施放大地之盾."
L["EarthShieldOptionsDesc"] = "如果为了滑鼠按钮改写像设置一样被选择, 当离开战斗盾被施放在最后一人或是被团队图腾插件分配. 预设用法: 离开战斗指向你大地之盾目标之后用右键点击按钮施放法术. 那么你可以指向任何一人, 然而用右键点击大地之盾仍然会施放在相同的人身上, 甚至在战斗中."
L["Earth Shield Tracker"] = "大地之盾"
L["ES Charges only"] = "只显示剩余次数"
L["ES Charges only desc"] = "关闭时间显示,在其位置上显示大地之盾的层数|n在你下一次施放大地之盾时生效"
L["ES Main Tank Desc"] = "滑鼠停留时显示了一个选单里面包含多达4个你队伍/团队中的主坦克"
L["ES Main Tank menu"] = "坦克选单"
L["esrecast"] = "重新施放 (最后一个目标/团队图腾)"
L["Leftclick"] = "鼠标左键点击"
L["Middle Button"] = "鼠标中键点击"
L["Rightclick"] = "鼠标右键点击"
L["Shield Tracker"] = "萨满护盾"
L["Trackers"] = "追踪器设置"
L["Weapon Buff Tracker"] = "武器增益"
L["WeaponDesc"] = "显示武器剩余增益时间.左键点击施放选择的武器增益. 右键点击开启选单选择增益, 一个图示显示两个增益. 第一个左键点击施放左边增益和第二个左键点击右边增益."

L["Color"] = "颜色"
L["disabled warnings desc"] = "即使追踪禁用, 到期增益警告还是会显示"
L["EarthShield warnings"] = "大地之盾警告"
L["Maelstrom notification"] = "漩涡武器提醒"
L["Messages"] = "信息"
L["Shield expiration warnings"] = "护盾到期警告"
L["Show warnings of disabled trackers"] = "禁用追踪显示警告"
L["Sound"] = "声音"
L["Totem Desctruction Desc"] = "警告如果图腾在到期前被销毁."
L["Totem Destruction Message"] = "图腾销毁信息"
L["Totem Expiration Desc"] = "图腾到期之后警告."
L["Totem Expiration Message"] = "图腾到期信息"
L["Totem Expiration Warning"] = "图腾到期警告"
L["Totem Warning Desc"] = "在图腾10秒到期前警告."
L["Warnings"] = "警告设置"
L["Weapon buff warnings"] = "武器增益警告"

L["Cooldowns"] = "冷却"
L["Duration"] = "期间"
L["ECD Button Size"] = "冷却图标大小"
L["ECD Font Size"] = "冷却字体大小"
L["EnhanceCDs"] = "冷却设置"
L["Flame Shock on top"] = "设置烈焰震击在顶部"
L["Flame Shock on top desc"] = "显示烈焰震击时间与气旋武器条在冷却计时器上方"
L["Hide OOC Desc"] = "改变这个设置下一次战斗才会生效"
L["Hide out of combat"] = "离开战斗隐藏"
L["Lava Surge Aura"] = "熔岩奔腾光环"
L["Lava Surge Aura Desc"] = "如果使用魔兽世界内置的熔岩奔腾特效 PowerAuras 则显示了一个光环围绕你的角色"
L["Lava Surge Glow"] = "熔岩奔腾辉光"
L["Lava Surge Glow Desc"] = "当熔岩奔腾特效发动时让熔岩爆发的冷却时间计时器和动作列按钮发出熔岩爆发的辉光"
L["Long Cooldowns"] = "长时间冷却"
L["Maelstrom Bar Height"] = "漩涡武器条高度"
L["OOC Alpha"] = "离开战斗透明度"
L["OOC Alpha Desc"] = "离开战斗控制不透明的按钮, 0 = 透明, 1 = 不透明"
L["Show OmniCC counters"] = "显示OmniCC计数"
L["Spells"] = "法术"

L["Arena"] = "竞技场"
L["Battleground"] = "战场"
L["Copy All"] = "复制所有"
L["Copy CC Settings"] = "复制控场设置"
L["Copy EnhanceCDs Settings"] = "复制增强冷却设置"
L["Copy Frame Positions"] = "复制框架位置"
L["Copy From"] = "复制于"
L["Copy General Settings"] = "复制综合设置"
L["Copy Settings"] = "复制设置"
L["Copy To"] = "复制到"
L["Copy Totem Settings"] = "复制图腾设置"
L["Copy Totem Timer Settings"] = "复制图腾计时器设置"
L["Copy Tracker Settings"] = "复制追踪器设置"
L["Copy Warnings"] = "复制警告"
L["Create Profile"] = "创建配置文件"
L["default"] = "默认"
L["Delete Profile"] = "删除配置文件"
L["Manage Profiles"] = "管理配置文件"
L["New Name"] = "新名称"
L["Party"] = "队伍"
L["Profile"] = "配置文件"
L["Profile already exists."] = "配置文件已存在."
L["Profiles"] = "配置文件"
L["Raid"] = "团队"
L["Really delete profile?"] = "确定要删除配置文件?"
L["Really reset frame positions?"] = "确定要重置框架位置?"
L["Reset Frame Positions"] = "重置框架位置"
L["Reset Profile"] = "重置配置文件"
L["Select Profiles"] = "选择配置文件"
L["Solo"] = "单人"
L["You cannot delete the default profile."] = "你不能删除默认配置文件."
L["You need to enter a profile name first."] = "配置文件必须输入一个名称."

end


L = LibStub("AceLocale-3.0"):NewLocale("TotemTimers", "ruRU")
if L then

L["Air Button"] = "Кнопки Воздуха"
L["Cooldown"] = "Кулдаун" -- Needs review
L["Ctrl-Leftclick to remove weapon buffs"] = "[Ctrl+Левый клик] - снять усиление с оружия"
L["Delete Set"] = "Удалить набор тотемов %u?"
L["Earth Button"] = "Кнопки Земли"
L["Fire Button"] = "Кнопки Огня"
L["Leftclick to cast %s"] = "[Левый клик] - применить %s"
L["Leftclick to cast spell"] = "[Левый клик] - применить заклинание"
L["Leftclick to load totem set"] = "[Левый клик] - загрузить набор тотемов %s"
L["Leftclick to open totem set menu"] = "[Левый клик] - открыть меню набора тотемов"
L["Long Cooldown"] = "Долгий кулдаун" -- Needs review
L["Maelstrom Notifier"] = "Водоворот готов!"
L["Middleclick to cast %s"] = "[Средний клик] - применить %s"
L["Next leftclick casts %s"] = "Следующий [Левый клик] - применить %s"
L["Reset"] = "TotemTimers сброшен!"
L["Rightclick to assign both %s and %s to leftclick"] = "[Правый клик] - назначить %s и %s на [левый клик]"
L["Rightclick to assign spell to leftclick"] = "[Правый клик] - назначить заклинание на [левый клик]"
L["Rightclick to assign totem to timer button"] = "Щелкните правой кнопкой мыши, чтобы назначить Тотем на кнопку таймера" -- Needs review
L["Rightclick to cast %s"] = "[Правый клик] - применить %s"
L["Rightclick to delete totem set"] = "[Правый клик] - удалить набор тотемов"
L["Rightclick to save active totem configuration as set"] = "[Правый клик] - сохранить активную конфигурацию тотемов как набор"
L["Shield removed"] = "%s снят"
L["Shift-Rightclick to assign spell to middleclick"] = "[Shift+Правый клик] назначить заклинание на [средний клик]"
L["Shift-Rightclick to assign spell to rightclick"] = "[Shift+Правый клик] назначить заклинание на [правый клик]"
L["Totem Destroyed"] = "%s разрушен"
L["Totem Expired"] = "%s истек"
L["Totem Expiring"] = "%s скоро исчезнет"
L["Water Button"] = "Кнопки Воды"
end


L = LibStub("AceLocale-3.0"):NewLocale("TotemTimers_GUI", "ruRU")
if L then

L["Air"] = "Воздух"
L["Automatic"] = "Авто"
L["Bottom"] = "снизу"
L["Cast Button 1"] = "Кнопка применения 1"
L["Cast Button 2"] = "Кнопка применения 2"
L["Clickthrough"] = "Клик насквозь"
L["Clickthrough Desc"] = "Делает кнопки таймеров прозрачными для нажатий"
L["Crowd Control"] = "Контроль персонажей"
L["Down"] = "Снизу"
L["Earth"] = "Земля"
L["Enable"] = "Включить"
L["Fire"] = "Огонь"
L["Flame Shock Duration"] = "Flame Shock Duration" -- Requires localization
L["Flame Shock Duration Desc"] = "Show Flame Shock Duration for Elemental" -- Requires localization
L["Flame Shock Duration Restoration"] = "Flame Shock for Restoration" -- Requires localization
L["Flame Shock Duration Restoration Desc"] = "Show Flame Shock Duration for Restoration" -- Requires localization
L["Left"] = "Слева"
L["Maelstrom Bar"] = "Maelstrom Bar" -- Requires localization
L["Maelstrom Bar Desc"] = "Show Maelstrom Bar for Enhancement and Elemental" -- Requires localization
L["Mana Bar"] = "Mana Bar" -- Requires localization
L["Mana Bar Desc"] = "Show Mana Bar for Restoration" -- Requires localization
L["none"] = "Нет"
L["Right"] = "Справа"
L["Top"] = "Сверху"
L["Totems"] = "Тотемы"
L["TotemTimers"] = true
L["Up"] = "верх"
L["Version"] = "Версия"
L["vertical"] = "Вертикальное"
L["Water"] = "Вода"

L["Blizz Style"] = "Стандартный"
L["Color Timer Bars"] = "Окраска таймеров"
L["Color Timer Bars according to their elements."] = "Окрашивать полосы таймеров в соответствии с их стихиями."
L["Debug"] = "Отладка"
L["Displays timer bars underneath times"] = "Показывать полосы времени под таймерами."
L["Fulmination Aura"] = "Аура Сверкание" -- Needs review
L["Fulmination Aura Desc"] = "Отображает ауру вокруг персонажа когда Щит молний стакается 9 раз, используя встроенный PowerAuras"
L["Fulmination Glow"] = "Fulmination Glow" -- Requires localization
L["Fulmination Glow Desc"] = "Lets the Earth Shock cooldown timer and action bar buttons containing Earth Shock glow if Lightning Shield gets to 9 stacks" -- Requires localization
L["General"] = "Общее"
L["Hide Blizzard Timers"] = "Скрыть стандартные таймеры"
L["Hide Default Totem Bar"] = "Скрыть стандартную панель"
L["Hide Default Totem Bar Desc"] = "Если вы снимите галку, вам следует перезагрузить UI"
L["Hide In Vehicles"] = "Скрывать в транспорте"
L["Hide In Vehicles Desc"] = "Скрывать TotemTimers во время управления транспортом. Не изменяйте этот параметр во время управления транспортом"
L["Lock"] = "Зафиксировать"
L["Locks the position of TotemTimers"] = "Зафиксировать TotemTimers"
L["RaidTotems"] = true
L["RaidTotems Desc"] = "Назначить набор тотемов, содержание которого будет определяться аддоном RaidTotems."
L["Red Flash Color"] = "Мерцание красным"
L["RedFlash Desc"] = "Если данная опция включена, заканчивающие свое действие тотемы будут мерцать красным; в других случаях они будут просто появляться и исчезать."
L["Reset All"] = "Сбросить все"
L["Reset Positions"] = "Сбросить позиции"
L["Show Key Bindings"] = "Назначения клавиш"
L["Shows key bindings on totem timers"] = "Отображать назначения клавиш на кнопках таймеров."
L["Shows tooltips on timer and totem buttons"] = "Отображать подсказки при наведении курсора на таймеры или кнопки тотемов."
L["Show Timer Bars"] = "Полосы времени"
L["Show Tooltips"] = "Подсказки"
L["Stop Pulse"] = "Пульсирование при окончании"
L["Stop Pulse Desc"] = "Пульсирование при окончании таймера"
L["Time Color"] = "Цвет времени"
L["Time Font"] = "Шрифт времени"
L["Timer Bar Color"] = "Цвет полосы времени"
L["Timer Bar Texture"] = "Текстура таймера"
L["Timers On Buttons"] = "Таймеры на кнопках"
L["Tooltips At Buttons"] = "Подсказки у кнопок"
L["Tooltips At Buttons Desc"] = "Показывать подсказки с правой стороны ТТ кнопок."

L["Advanced Options"] = "Расширенные опции"
L["Always Visible Desc"] = "Меню тотемов будет всегда отображаться и будет подвижно как панель команд."
L["Arrangement"] = "Расположение"
L["Basic layout of the four timer buttons, loose lets you move them individually"] = "Базовая схема из четырех кнопок таймера, позволяет свободно перемещать их по отдельности."
L["box"] = "Блок"
L["Button Size"] = "Размер кнопки"
L["Cast Button Position"] = "Позиция кнопки применения"
L["Cast Button Position Desc"] = "Установка позиции дополнительных кнопок тотемов, рядом с таймерами."
L["Cast Button Size"] = "Размер кнопки применения"
L["Cast Button Size Desc"] = "Установка размера дополнительных кнопок тотемов относительно размера таймеров."
L["Enable Pulse Bar"] = "Пульсация"
L["Enables the four totem timer buttons and menus"] = "Включить кнопки и меню таймеров четырёх тотемов."
L["horizontal"] = "Горизонтальное"
L["Keybindings desc"] = "Если данная опция включена, то при отображении меню тотемов кнопкам тотемов будут назначены клавиши 1-9.|nЧтобы настройки вступили в силу, вы должны перезайти в игру или перезагрузить UI."
L["loose"] = "Свободное"
L["Mini Icons Desc"] = "Показывает небольшие иконки в нижнем правом углу кнопки таймера, которые отображают иконку пересоздаваемого тотема."
L["Open On Rightclick"] = "Открыть правым кликом"
L["Player Range"] = "Досягаемость игрока"
L["Player Range Desc"] = "Показывает красные точки на таймере тотема, если игрок вне досягаемости."
L["Pulse desc"] = "Показывает внутри таймера статус проковпульсации зеленым цветом, это означает что при заполнение всей иконки таймера зеленым цветом тотем прокает/пульсирует."
L["Raid Member Range"] = "Досягаемость участника рейда"
L["Raid Range Tooltip"] = "Подсказка досягаемости рейда"
L["Range Desc"] = "Показывает в левом нижнем углу, сколько участников рейда не получают эффект от вашего тотема"
L["Reverse Key Bindings"] = "Противоположные клавиши назначения"
L["Reverse Key Desc"] = "Порядок назначения клавиш 9-1 вместо 1-9.|nЧтобы настройки вступилибы в силу, вы должны перезайти в игру или перезагрузить UI."
L["Rightclick Desc"] = "Открывать меню тотемов по правому клику вместо открытия наведением курсора на кнопку таймера. Тотемы могут быть убраны с помощью средней кнопки мыши вместо правого клика."
L["RR Tooltip Desc"] = "При наведении мыши на таймер тотема, показывает список участников рейда, которые вне досягаемости вашего тотема."
L["Scales the timer buttons"] = "Установка размера кнопок таймера."
L["Scaling"] = "Масштабирование"
L["Sets the font size of time strings"] = "Установка размера шрифта строки таймера."
L["Sets the format in which times are displayed"] = "Установка формата отображения времени."
L["Sets the space between timer buttons"] = "Установка промежутка между кнопками таймеров."
L["Sets the space between timer buttons and timer bars"] = "Установка промежутка между кнопками таймеров и полосами времени."
L["Sets the width of timer bars."] = "Установка ширины полос времени."
L["Show Mini Icons"] = "Показать мини иконки"
L["Show Totem Cooldowns"] = "Восстановление тотемов"
L["Spacing"] = "Промежуток"
L["Timer Bar Position"] = "Позиция времени"
L["Timer Bar Position Desc"] = "Установка с какой стороны будет отображаться иконки таймера."
L["Timer Bar Width"] = "Ширина полосы времени"
L["Timer Bar Width Desc"] = "Установка ширины полос времени."
L["Timer Button 1"] = "Таймер 1"
L["Timer Button 2"] = "Таймер 2"
L["Timer Button 3"] = "Таймер 3"
L["Timer Button 4"] = "Таймер 4"
L["Timers"] = "Таймеры"
L["Timers On Buttons Desc"] = "Таймеры будут отображаться на кнопках а не рядом с ними. Если включено, отслеживание оружия будет показывать только время оружия в правой руке при владении двуручным оружием."
L["Time Size"] = "Размер времени"
L["Time Spacing"] = "Промежуток времени"
L["Time Style"] = "Стиль времени"
L["Totem Cooldowns desc"] = "Показывает восстановление всех тотемов с более длительным восстановлением в качестве дополнительных полос таймера."
L["Totem menu direction"] = "Направление меню тотема"
L["Totem menu direction desc"] = "Установка направления открытия меню тотемов. Автоматически определяет направление полагаясь на позицию таймера."
L["Totem Menu Key Bindings"] = "Включить назначение клавиш"
L["Totem Menus Always Visible"] = "Всегда отображать меню тотемов"
L["Totem Menu Spacing"] = "Промежуток меню тотемов"
L["Totem Menu Spacing Desc"] = "Установка промежутка кнопок в меню тотемов. Применимо только когда меню отображается всегда."

L["Ankh Tracker"] = "Таймер Восстания из мертвых"
L["Ankh Tracker Desc"] = "Показывает оставшееся время восстановления вашей способности реинкарнации, а также выводит количество крестов в ваших сумках. Также используется для сохранения и загрузки наборов тотемов."
L["Button 4"] = "Кнопка 4"
L["EarthShieldDesc"] = "Отображать остаток времени Щита Земли и его заряды. Может быть использован для применения Щита Земли."
L["EarthShieldOptionsDesc"] = "Если 'пересоздать' отмечено в опциях для кнопки мыши, щит будет применяться на последнюю персону, на которую он был наложен вне боя, или персона будет задаваться модификацией RaidTotems."
L["Earth Shield Tracker"] = "Отслеживание Щита Земли"
L["ES Charges only"] = "Charges only" -- Requires localization
L["ES Charges only desc"] = "Disables the time display and shows ES charges in its place|nChanges take effect the next time you cast ES" -- Requires localization
L["ES Main Tank Desc"] = "On mouseover shows a menu containing up to 4 main tanks of your raid/party" -- Requires localization
L["ES Main Tank menu"] = "Main Tank menu" -- Requires localization
L["esrecast"] = "пересоздать (последняя цель/RaidTotems)"
L["Leftclick"] = "Левый клик"
L["Middle Button"] = "Средняя кнопка"
L["Rightclick"] = "Правый клик"
L["Shield Tracker"] = "Отслеживание щита"
L["Trackers"] = "Отслеживание"
L["Weapon Buff Tracker"] = "Отслеживание усилений на оружии"
L["WeaponDesc"] = "Отображать остаток времени ваших усилений оружия. Левый клик применяет выбранное усиление, правый клик открывает меню для выбора усиления. Иконка отображающая два улучшения, по ней первый левый клик применит улучшение на левое оружие, второй левый клик на правое."

L["Color"] = "Цвет"
L["disabled warnings desc"] = "Сообщения об истечении эффектов будут отображаться, даже если отслеживание отключено."
L["EarthShield warnings"] = "Сообщения о щите земли"
L["Maelstrom notification"] = "Сообщения о Водовороте"
L["Messages"] = "Сообщения"
L["Shield expiration warnings"] = "Сообщения о спадении щита"
L["Show warnings of disabled trackers"] = "Вывод предупреждений отключенных отслеживаний"
L["Sound"] = "Звук"
L["Totem Desctruction Desc"] = "Сообщать если тотем был уничтожен до его истечения."
L["Totem Destruction Message"] = "Сообщения об уничтожении тотема"
L["Totem Expiration Desc"] = "Сообщать после истечения тотема."
L["Totem Expiration Message"] = "Сообщения об исчезании тотемов"
L["Totem Expiration Warning"] = "Предупреждения об исчезании тотемов"
L["Totem Warning Desc"] = "Предупреждать за 10 секунд до исчезания тотема."
L["Warnings"] = "Предупреждение"
L["Weapon buff warnings"] = "Сообщения об усилениях оружия"

L["Cooldowns"] = "Кулдауны" -- Needs review
L["Duration"] = "Длительность"
L["ECD Button Size"] = "Размер кнопки ECD"
L["ECD Font Size"] = "Высота шрифта ECD"
L["EnhanceCDs"] = true
L["Flame Shock on top"] = "Огненный шок сверху"
L["Flame Shock on top desc"] = "Показывает полоски Огненного Шока и Водоворота над кулдаунами"
L["Hide OOC Desc"] = "Изменение этой настройки вступит в силу после следующего боя"
L["Hide out of combat"] = "Скрыть вне боя"
L["Lava Surge Aura"] = "Аура Волны Лавы"
L["Lava Surge Aura Desc"] = "Отображает ауру вокруг персонажа если срабатывает Волна Лавы, используя встроенный PowerAuras"
L["Lava Surge Glow"] = "Сверкание Волны Лавы"
L["Lava Surge Glow Desc"] = "Позволяет таймеру Выброса Лавы и всем экшнбарам с Выбросом Лавы сверкать при срабатывании Волны Лавы"
L["Long Cooldowns"] = "Долгие кулдауны" -- Needs review
L["Maelstrom Bar Height"] = "Высота полосы водоворота"
L["OOC Alpha"] = "Прозрачность вне боя"
L["OOC Alpha Desc"] = "Настройка прозрачности кнопок вне боя, 0 = прозрачный, 1 = непрозрачный"
L["Show OmniCC counters"] = "Показывать счетчики OmniCC"
L["Spells"] = "Заклинания" -- Needs review

L["Arena"] = "Арена" -- Needs review
L["Battleground"] = "Поле боя" -- Needs review
L["Copy All"] = "Копировать все" -- Needs review
L["Copy CC Settings"] = "Copy CC Settings" -- Requires localization
L["Copy EnhanceCDs Settings"] = "Copy EnhanceCDs Settings" -- Requires localization
L["Copy Frame Positions"] = "Копировать позиции окна" -- Needs review
L["Copy From"] = "Скопировать из" -- Needs review
L["Copy General Settings"] = "Копировать общие настройки" -- Needs review
L["Copy Settings"] = "Копировать настройки" -- Needs review
L["Copy To"] = "Копировать в" -- Needs review
L["Copy Totem Settings"] = "Копировать настройки тотемов" -- Needs review
L["Copy Totem Timer Settings"] = "Копировать настройки таймеров тотемов" -- Needs review
L["Copy Tracker Settings"] = "Копировать настройки трекера" -- Needs review
L["Copy Warnings"] = "Копировать предупреждения" -- Needs review
L["Create Profile"] = "Создать профиль" -- Needs review
L["default"] = "По умолчанию" -- Needs review
L["Delete Profile"] = "Удалить профиль" -- Needs review
L["Manage Profiles"] = "Управление профилями" -- Needs review
L["New Name"] = "Новое имя" -- Needs review
L["Party"] = "Группа" -- Needs review
L["Profile"] = "Профиль" -- Needs review
L["Profile already exists."] = "Профиль уже существует." -- Needs review
L["Profiles"] = "Профили" -- Needs review
L["Raid"] = "Рейд" -- Needs review
L["Really delete profile?"] = "Действительно удалить профиль?" -- Needs review
L["Really reset frame positions?"] = "Действительно сбросить позиции окон?" -- Needs review
L["Reset Frame Positions"] = "Сбросить позиции окон" -- Needs review
L["Reset Profile"] = "Сбросить профиль" -- Needs review
L["Select Profiles"] = "Выбрать профиль" -- Needs review
L["Solo"] = "Соло" -- Needs review
L["You cannot delete the default profile."] = "Вы не можете удалить профиль по умолчанию." -- Needs review
L["You need to enter a profile name first."] = "Вам необходимо ввести имя профиля первым." -- Needs review
end

local L = LibStub("AceLocale-3.0"):NewLocale("TotemTimers", "koKR")
if L then
L["Air Button"] = "바람 버튼"
L["Cooldown"] = "재사용 대기시간" -- Needs review
L["Ctrl-Leftclick to remove weapon buffs"] = "Ctrl+왼쪽 클릭시 무기 버프 제거"
L["Delete Set"] = "토템 %u 세트를 삭제합니까?"
L["Earth Button"] = "대지 버튼"
L["Fire Button"] = "불 버튼"
L["Leftclick to cast %s"] = "왼쪽 클릭시 %s 시전"
L["Leftclick to cast spell"] = "왼쪽 클릭시 주문 시전"
L["Leftclick to load totem set"] = "왼쪽 클릭시 %s 토템 세트를 불려옵니다." -- Needs review
L["Leftclick to open totem set menu"] = "왼쪽 클릭시 토템 세트 메뉴를 엽니다."
L["Long Cooldown"] = "긴 재사용 대기시간" -- Needs review
L["Maelstrom Notifier"] = "소용돌이치는 무기 준비!"
L["Middleclick to cast %s"] = "가운데 클릭시 %s 시전"
L["Next leftclick casts %s"] = "다음 왼쪽 클릭시 %s 시전"
L["Reset"] = "TotemTimers 초기화!"
L["Rightclick to assign both %s and %s to leftclick"] = "오른쪽 클릭시 주문 지정, 왼쪽 클릭시 %s와 %s 주문 시전"
L["Rightclick to assign spell to leftclick"] = "왼쪽 클릭시 주문 지정, 오른쪽 클릭시 주문 시전"
L["Rightclick to assign totem to timer button"] = "오른쪽 클릭시 타이머 버튼에 토템 할당" -- Needs review
L["Rightclick to cast %s"] = "오른쪽 클릭시 %s 시전"
L["Rightclick to delete totem set"] = "오른쪽 클릭시 토템 세트를 삭제합니다."
L["Rightclick to save active totem configuration as set"] = "오른쪽 클릭시 세트와같은 사용한 토템 구성을 저장합니다."
L["Shield removed"] = "%s 효과가 사라졌습니다."
L["Shift-Rightclick to assign spell to middleclick"] = "Shift-오른쪽 클릭시 주문 지정, 가운데 클릭시 주문 시전"
L["Shift-Rightclick to assign spell to rightclick"] = "Shift-오른쪽 클릭시 주문 지정, 오른쪽 클릭시 주문 시전"
L["Totem Destroyed"] = "%s|1이;가; 파괴되었습니다."
L["Totem Expired"] = "%s의 지속시간이 만료되었습니다."
L["Totem Expiring"] = "%s의 지속시간이 얼마 남지 않았습니다."
L["Water Button"] = "물 버튼"
end

L = LibStub("AceLocale-3.0"):NewLocale("TotemTimers_GUI", "koKR")
if L then

L["Air"] = "바람"
L["Automatic"] = "자동"
L["Bottom"] = "하단"
L["Cast Button 1"] = "시전 버튼 1"
L["Cast Button 2"] = "시전 버튼 2"
L["Clickthrough"] = "클릭 사용 안함" -- Needs review
L["Clickthrough Desc"] = "타이머 버튼 클릭 기능을 사용하지 않습니다." -- Needs review
L["Crowd Control"] = "군중 제어" -- Needs review
L["Down"] = "아래"
L["Earth"] = "대지"
L["Enable"] = "사용"
L["Fire"] = "불"
L["Flame Shock Duration"] = "Flame Shock Duration" -- Requires localization
L["Flame Shock Duration Desc"] = "Show Flame Shock Duration for Elemental" -- Requires localization
L["Flame Shock Duration Restoration"] = "Flame Shock for Restoration" -- Requires localization
L["Flame Shock Duration Restoration Desc"] = "Show Flame Shock Duration for Restoration" -- Requires localization
L["Left"] = "좌측"
L["Maelstrom Bar"] = "Maelstrom Bar" -- Requires localization
L["Maelstrom Bar Desc"] = "Show Maelstrom Bar for Enhancement and Elemental" -- Requires localization
L["Mana Bar"] = "Mana Bar" -- Requires localization
L["Mana Bar Desc"] = "Show Mana Bar for Restoration" -- Requires localization
L["none"] = "없음"
L["Right"] = "우측"
L["Top"] = "상단"
L["Totems"] = "토템"
L["TotemTimers"] = true
L["Up"] = "위"
L["Version"] = "버전"
L["vertical"] = "수직"
L["Water"] = "물"

L["Blizz Style"] = "기본 스타일"
L["Color Timer Bars"] = "타이머 바 색상"
L["Color Timer Bars according to their elements."] = "요소에 따른 타이머 바의 색상을 변경합니다."
L["Debug"] = "디버그"
L["Displays timer bars underneath times"] = "시간 아래에 타이머 바를 표시합니다."
L["Fulmination Aura"] = "성난 부르짖음 효과"
L["Fulmination Aura Desc"] = "번개 보호막 9중첩 효과 발동시 PowerAuras처럼 캐릭터 주변에 효과를 표시합니다." -- Needs review
L["Fulmination Glow"] = "성난 부르짖음 깜박임"
L["Fulmination Glow Desc"] = "번개 보호막 9중첩 효과 발동시 타이머와 행동 단축바의 대지 충격 아이콘에 깜박임 효과를 표시합니다." -- Needs review
L["General"] = "일반"
L["Hide Blizzard Timers"] = "블리자드 타이머 숨김"
L["Hide Default Totem Bar"] = "기본 토템 바 숨김"
L["Hide Default Totem Bar Desc"] = "선택을 취소할 경우 효과 적용을 위해 당신의 UI를 재시작하시기 바랍니다."
L["Hide In Vehicles"] = "탑승시 숨김"
L["Hide In Vehicles Desc"] = "차량 탑승시 토템 타이머를 숨깁니다. 탑승중 이 설정은 변경되지 않습니다."
L["Lock"] = "잠금"
L["Locks the position of TotemTimers"] = "토템 타이머의 위치를 잠금니다."
L["RaidTotems"] = true
L["RaidTotems Desc"] = "RaidTotems 애드온에 의해 선정된 다중 주문을 시전합니다."
L["Red Flash Color"] = "붉은색 반짝임 색상"
L["RedFlash Desc"] = "사용시 만료중에 있는 토템은 적색으로 반짝입니다. 그외에는 밝았다 어두워집니다."
L["Reset All"] = "전체 초기화"
L["Reset Positions"] = "위치 초기화"
L["Show Key Bindings"] = "단축키 표시"
L["Shows key bindings on totem timers"] = "토템 타이머 위에 단축키를 표시합니다."
L["Shows tooltips on timer and totem buttons"] = "타이머나 토템 버튼 위에 마우스 오버시 툴팁을 표시합니다."
L["Show Timer Bars"] = "타이버 바 표시"
L["Show Tooltips"] = "툴팁 표시"
L["Stop Pulse"] = "맥박 중지"
L["Stop Pulse Desc"] = "\"타이머가 중지되면 해당 아이콘을 크게 표시하는 맥박을 사용하지 않습니다.\""
L["Time Color"] = "시간 색상"
L["Time Font"] = "시간 글꼴"
L["Timer Bar Color"] = "타이머 바 색상"
L["Timer Bar Texture"] = "타이머 바 무늬"
L["Timers On Buttons"] = "버튼에 타이머"
L["Tooltips At Buttons"] = "버튼의 툴팁"
L["Tooltips At Buttons Desc"] = "TT 버튼 위에 툴팁을 표시합니다."

L["Advanced Options"] = "고급 옵션"
L["Always Visible Desc"] = "토템 메뉴를 항상 표시하고 행동 단축바처럼 드래그 할 수 있습니다."
L["Arrangement"] = "배열"
L["Basic layout of the four timer buttons, loose lets you move them individually"] = "개별 타이머 버튼 4개의 기본 배치를 당신은 개인적으로 이동시킬 수 있습니다."
L["box"] = "박스"
L["Button Size"] = "버튼 크기"
L["Cast Button Position"] = "시전 버튼 위치"
L["Cast Button Position Desc"] = "토템 타이머에 추가 사용자 토템 버튼의 위치를 설정합니다."
L["Cast Button Size"] = "시전 버튼 크기"
L["Cast Button Size Desc"] = "토템 타이머에 추가 사용자 토템 버튼의 크기를 설정합니다."
L["Enable Pulse Bar"] = "진행 과정바 사용"
L["Enables the four totem timer buttons and menus"] = "4개의 토템 타이머 버튼과 메뉴를 사용합니다."
L["horizontal"] = "수평"
L["Keybindings desc"] = "사용시, 토템 메뉴를 표시할 때 토템 버튼에 1-9의 단축키를 표시합니다.|n이 설정의 효과 적용을 위해 당신은 UI를 재시작 합니다."
L["loose"] = "개별"
L["Mini Icons Desc"] = "타이머 버튼의 우측 하단에 재시전 할 수 있는 토템 버튼을 지시하는 작은 아이콘을 표시합니다."
L["Open On Rightclick"] = "오른쪽 클릭시 열기"
L["Player Range"] = "플레이어 거리"
L["Player Range Desc"] = "플레이어가 범위를 벗어나면 토템 타이머 위에 붉은 점으로 표시합니다."
L["Pulse desc"] = "타이머 내부에 토템의 지속 시간이 채워질 때까지의 과정을 녹색의 상태 바로 표시합니다."
L["Raid Member Range"] = "공격대원 거리"
L["Raid Range Tooltip"] = "공격대 거리 툴팁"
L["Range Desc"] = "왼쪽 모서리에 당신의 토템 버프를 받지 못하는 공격대원을 수를 표시합니다."
L["Reverse Key Bindings"] = "단축키 반대로"
L["Reverse Key Desc"] = "단축키 순서를 1-9에서 9-1로 변경합니다.|n이 설정의 효과 적용을 위해 당신은 UI를 재시작 합니다."
L["Rightclick Desc"] = "타이머 버튼에 오른쪽 클릭시 토템 메뉴를 엽니다. 가운데 버튼 클릭시 해당 토템을 회수합니다."
L["RR Tooltip Desc"] = "토템 타이머에 마우스 오버시 당신의 토템에서 거리를 벗어난 공격대원들의 목록을 표시합니다."
L["Scales the timer buttons"] = "타이머 버튼 크기를 설정합니다."
L["Scaling"] = "비율"
L["Sets the font size of time strings"] = "시간 글꼴의 크기를 설정합니다."
L["Sets the format in which times are displayed"] = "어떤 형식으로 시간을 표시할지 설정합니다."
L["Sets the space between timer buttons"] = "타이머 버튼의 간격을 설정합니다."
L["Sets the space between timer buttons and timer bars"] = "타이머 버튼과 타이머 바의 간격을 설정합니다."
L["Sets the width of timer bars."] = "타이머 바의 너비를 설정합니다."
L["Show Mini Icons"] = "작은 아이콘 표시"
L["Show Totem Cooldowns"] = "토템 재사용 대기시간 표시"
L["Spacing"] = "간격"
L["Timer Bar Position"] = "타이머 바 위치"
L["Timer Bar Position Desc"] = "시간 타이머 아이콘을 어느 위치에 표시할지 설정합니다."
L["Timer Bar Width"] = "타이머 바 너비"
L["Timer Bar Width Desc"] = "타이머 바의 너비를 설정합니다."
L["Timer Button 1"] = "타이머 버튼 1"
L["Timer Button 2"] = "타이머 버튼 2"
L["Timer Button 3"] = "타이머 버튼 3"
L["Timer Button 4"] = "타이머 버튼 4"
L["Timers"] = "타이머"
L["Timers On Buttons Desc"] = "버튼 위에 타이머를 표시합니다. 쌍수 무기일때 추적기에는 주 무기의 시간을 표시합니다."
L["Time Size"] = "타이머 크기"
L["Time Spacing"] = "타이머 간격"
L["Time Style"] = "타이머 스타일"
L["Totem Cooldowns desc"] = "재사용 대기시간을 가지고 있는 모든 토템의 대기시간을 타이머 가운데에 표시합니다."
L["Totem menu direction"] = "토템 메뉴 방향"
L["Totem menu direction desc"] = "토템 메뉴가 열릴때 방향입니다. 자동은 타이머 위치를 기준으로 방향을 결정합니다."
L["Totem Menu Key Bindings"] = "토템 메뉴 단축키"
L["Totem Menus Always Visible"] = "토템 메뉴 항상 표시"
L["Totem Menu Spacing"] = "토템 메뉴 간격"
L["Totem Menu Spacing Desc"] = "토템 메뉴 버튼 간격을 설정합니다. 메뉴 항상 표시때 적용됩니다."

L["Ankh Tracker"] = "윤회 추적"
L["Ankh Tracker Desc"] = "가방에 있는 십자가의 수량과 윤회 능력의 남은 재사용 대기시간을 표시합니다."
L["Button 4"] = "버튼 4"
L["EarthShieldDesc"] = "대지 보호막의 남은 시간과 갯수를 표시합니다. 클릭시 대지 보호막을 시전합니다."
L["EarthShieldOptionsDesc"] = "만약 '재시전'을 선택한다면, 마지막으로 보호막을 받은 플레이어에게 시전을 하거나 RaidTotems 애드온에 의해 선택된 플레이어에게 시전합니다."
L["Earth Shield Tracker"] = "대지 보호막 추적"
L["ES Charges only"] = "Charges only" -- Requires localization
L["ES Charges only desc"] = "Disables the time display and shows ES charges in its place|nChanges take effect the next time you cast ES" -- Requires localization
L["ES Main Tank Desc"] = "마우스 오버시 당신의 공격대/파티원의 방어전담 4명까지 메뉴에 표시합니다." -- Needs review
L["ES Main Tank menu"] = "ES 메인 탱커 메뉴"
L["esrecast"] = "재시전 (마지막 대상/RaidTotems)"
L["Leftclick"] = "왼쪽 클릭"
L["Middle Button"] = "가운데 클릭"
L["Rightclick"] = "오른쪽 클릭"
L["Shield Tracker"] = "보호막 추척"
L["Trackers"] = "추적기"
L["Weapon Buff Tracker"] = "무기 버프 추적"
L["WeaponDesc"] = "오른쪽 클릭을 통해 시전할 버프를 선택하고, 첫번째 왼쪽 클릭시 주무기에 버프 시전을 하고 두번째 왼쪽 클릭시 보조무기에 버프를 시전합니다."

L["Color"] = "색상"
L["disabled warnings desc"] = "추적기를 사용하지 않아도, 버프 만료 및 사라짐 경고를 표시합니다."
L["EarthShield warnings"] = "대지의 보호막 경고"
L["Maelstrom notification"] = "소용돌이치는 무기 경고"
L["Messages"] = "메시지"
L["Shield expiration warnings"] = "보호막 만료 경고"
L["Show warnings of disabled trackers"] = "사용하지 않는 추적기 경고 표시"
L["Sound"] = "효과음"
L["Totem Desctruction Desc"] = "토템 만료전 파괴시 경고합니다."
L["Totem Destruction Message"] = "토템 파괴 메시지"
L["Totem Expiration Desc"] = "토템 만료시 경고합니다."
L["Totem Expiration Message"] = "토템 만료 메시지"
L["Totem Expiration Warning"] = "토템 만료 경고"
L["Totem Warning Desc"] = "토템 만료 10초전 경고합니다."
L["Warnings"] = "경고"
L["Weapon buff warnings"] = "무기 버프 경고"

L["Cooldowns"] = "재사용 대기시간" -- Needs review
L["Duration"] = "지속시간"
L["ECD Button Size"] = "ECD 버튼 크기"
L["ECD Font Size"] = "ECD 글꼴 크기"
L["EnhanceCDs"] = true
L["Flame Shock on top"] = "상단에 화염 충격"
L["Flame Shock on top desc"] = "화염 충격 지속시간과 소용돌이치는 무기 바에 유지시간을 표시합니다." -- Needs review
L["Hide OOC Desc"] = "이 설정의 효과는 다음 전투 후 변경됩니다."
L["Hide out of combat"] = "비 전투 상태시 숨김"
L["Lava Surge Aura"] = "용암 쇄도 효과"
L["Lava Surge Aura Desc"] = "용암 쇄도 효과 발동시 PowerAuras처럼 캐릭터 주변에 효과를 표시합니다." -- Needs review
L["Lava Surge Glow"] = "용암 쇄도 깜박임"
L["Lava Surge Glow Desc"] = "용암 쇄도 효과 발동시 타이머와 행동 단축바의 용암 쇄도 아이콘에 깜박임 효과를 표시합니다." -- Needs review
L["Long Cooldowns"] = "긴 재사용 대기시간" -- Needs review
L["Maelstrom Bar Height"] = "소용돌이치는 무기 바 높이"
L["OOC Alpha"] = "OOC 투명도"
L["OOC Alpha Desc"] = "전투 상태시 버튼의 불투명도를 조절합니다, 0 = 투명, 1 = 불투명"
L["Show OmniCC counters"] = "OmniCC 카운터 표시"
L["Spells"] = "주문" -- Needs review

L["Arena"] = "투기장" -- Needs review
L["Battleground"] = "전장" -- Needs review
L["Copy All"] = "전체 복사" -- Needs review
L["Copy CC Settings"] = "CC 설정 복사" -- Needs review
L["Copy EnhanceCDs Settings"] = "EnhanceCDs 설정 복사" -- Needs review
L["Copy Frame Positions"] = "창 위치 복사" -- Needs review
L["Copy From"] = "Copy From" -- Requires localization
L["Copy General Settings"] = "일반 설정 복사" -- Needs review
L["Copy Settings"] = "복사 설정" -- Needs review
L["Copy To"] = "Copy To" -- Requires localization
L["Copy Totem Settings"] = "토템 설정 복사" -- Needs review
L["Copy Totem Timer Settings"] = "토템 타이머 설정 복사" -- Needs review
L["Copy Tracker Settings"] = "추적 설정 복사" -- Needs review
L["Copy Warnings"] = "복사 경고" -- Needs review
L["Create Profile"] = "새로운 프로필" -- Needs review
L["default"] = "기본값" -- Needs review
L["Delete Profile"] = "프로필 삭제" -- Needs review
L["Manage Profiles"] = "프로필 관리" -- Needs review
L["New Name"] = "새로운 이름" -- Needs review
L["Party"] = "파티" -- Needs review
L["Profile"] = "프로필" -- Needs review
L["Profile already exists."] = "프로필이 이미 존재합니다." -- Needs review
L["Profiles"] = "프로필" -- Needs review
L["Raid"] = "공격대" -- Needs review
L["Really delete profile?"] = "정말 프로필을 삭제하시겠습니까?" -- Needs review
L["Really reset frame positions?"] = "정말 창 위치를 재설정 하시겠습니까?" -- Needs review
L["Reset Frame Positions"] = "창 위치 초기화" -- Needs review
L["Reset Profile"] = "프로필 초기화" -- Needs review
L["Select Profiles"] = "프로필 선택" -- Needs review
L["Solo"] = "솔로잉" -- Needs review
L["You cannot delete the default profile."] = "당신은 기본 프로필을 삭제할 수 없습니다." -- Needs review
L["You need to enter a profile name first."] = "프로필 이름을 입력하여야합니다." -- Needs review

end


L = LibStub("AceLocale-3.0"):NewLocale("TotemTimers", "zhTW")
if L then
L["Air Button"] = "風之圖騰"
L["Cooldown"] = "冷卻"
L["Ctrl-Leftclick to remove weapon buffs"] = "Ctrl-左鍵點擊移除武器增益"
L["Delete Set"] = "刪除圖騰設定%u?"
L["Earth Button"] = "大地圖騰"
L["Fire Button"] = "火焰圖騰"
L["Leftclick to cast %s"] = "左鍵點擊施放%s"
L["Leftclick to cast spell"] = "左鍵點擊施放法術"
L["Leftclick to load totem set"] = "左鍵加載圖騰設置 %s"
L["Leftclick to open totem set menu"] = "左鍵打開設置介面"
L["Long Cooldown"] = "長時冷卻"
L["Maelstrom Notifier"] = "漩渦就緒!"
L["Middleclick to cast %s"] = "中鍵點擊施放%s"
L["Next leftclick casts %s"] = "下次左鍵點擊施放%s"
L["Reset"] = "TotemTimers 已重置！"
L["Rightclick to assign both %s and %s to leftclick"] = "右鍵點擊分配%s和%s到左鍵點擊"
L["Rightclick to assign spell to leftclick"] = "右鍵點擊分配法術到左鍵點擊"
L["Rightclick to assign totem to timer button"] = "右鍵點擊以分配圖騰到計時器按鈕"
L["Rightclick to cast %s"] = "右鍵點擊施放%s"
L["Rightclick to delete totem set"] = "右鍵刪除圖騰設置"
L["Rightclick to save active totem configuration as set"] = "右鍵保存激活的圖騰設置"
L["Shield removed"] = "%s 移除"
L["Shift-Rightclick to assign spell to middleclick"] = "Shift-右鍵點擊分配法術到中鍵點擊"
L["Shift-Rightclick to assign spell to rightclick"] = "Shift-右鍵點擊分配法術到右鍵點擊"
L["Totem Destroyed"] = "%s 已摧毀"
L["Totem Expired"] = "%s 到期了"
L["Totem Expiring"] = "%s 快到期"
L["Water Button"] = "水之圖騰"
end

L = LibStub("AceLocale-3.0"):NewLocale("TotemTimers_GUI", "zhTW")
if L then
L["Air"] = "風之"
L["Automatic"] = "自動"
L["Bottom"] = "置底"
L["Cast Button 1"] = "施法按鈕1"
L["Cast Button 2"] = "施法按鈕2"
L["Clickthrough"] = "點擊穿越"
L["Clickthrough Desc"] = "取消任何點擊功能按鈕的計時器"
L["Crowd Control"] = "控場選項"
L["Down"] = "下"
L["Earth"] = "大地"
L["Enable"] = "啟用"
L["Fire"] = "火焰"
L["Flame Shock Duration"] = "Flame Shock Duration" -- Requires localization
L["Flame Shock Duration Desc"] = "Show Flame Shock Duration for Elemental" -- Requires localization
L["Flame Shock Duration Restoration"] = "Flame Shock for Restoration" -- Requires localization
L["Flame Shock Duration Restoration Desc"] = "Show Flame Shock Duration for Restoration" -- Requires localization
L["Left"] = "左"
L["Maelstrom Bar"] = "Maelstrom Bar" -- Requires localization
L["Maelstrom Bar Desc"] = "Show Maelstrom Bar for Enhancement and Elemental" -- Requires localization
L["Mana Bar"] = "Mana Bar" -- Requires localization
L["Mana Bar Desc"] = "Show Mana Bar for Restoration" -- Requires localization
L["none"] = "無"
L["Right"] = "右"
L["Top"] = "置頂"
L["Totems"] = "圖騰"
L["TotemTimers"] = true
L["Up"] = "上"
L["Version"] = "版本"
L["vertical"] = "豎直方向"
L["Water"] = "水之"

L["Blizz Style"] = "內建格式"
L["Color Timer Bars"] = "計時條上色"
L["Color Timer Bars according to their elements."] = "根據元素計時條上色"
L["Debug"] = "除錯"
L["Displays timer bars underneath times"] = "顯示計時條在時間下方"
L["Fulmination Aura"] = "撼天雷電光環"
L["Fulmination Aura Desc"] = "如果使用魔獸世界內置的PowerAuras並且閃電盾堆疊到9層時，則顯示了一個光環圍繞你的角色。"
L["Fulmination Glow"] = "撼天雷電輝光"
L["Fulmination Glow Desc"] = "如果閃電盾堆疊到9層時，讓大地震擊冷卻計時器與動作列按鈕顯示大地震擊輝光。"
L["General"] = "一般"
L["Hide Blizzard Timers"] = "隱藏內建計時"
L["Hide Default Totem Bar"] = "隱藏預設圖騰條"
L["Hide Default Totem Bar Desc"] = "如果你取消這個你應該重新載入你的界面。"
L["Hide In Vehicles"] = "騎乘時隱藏"
L["Hide In Vehicles Desc"] = "騎乘時隱藏TotemTimers。騎乘時不要改變設定"
L["Lock"] = "鎖定"
L["Locks the position of TotemTimers"] = "鎖定TotemTimers位置"
L["RaidTotems"] = "團隊圖騰"
L["RaidTotems Desc"] = "設定圖騰組法術根據團隊圖騰插件發送的圖騰來分配。"
L["Red Flash Color"] = "紅光閃爍"
L["RedFlash Desc"] = "如果啟用到期時間紅光閃爍，否則淡入或淡出。"
L["Reset All"] = "重置全部"
L["Reset Positions"] = "重置位置"
L["Show Key Bindings"] = "顯示快捷鍵"
L["Shows key bindings on totem timers"] = "在圖騰計時上顯示快捷鍵"
L["Shows tooltips on timer and totem buttons"] = "在計時跟圖騰按鈕上顯示提示"
L["Show Timer Bars"] = "顯示計時條"
L["Show Tooltips"] = "顯示提示"
L["Stop Pulse"] = "停止脈衝"
L["Stop Pulse Desc"] = "\"如果一個計時器停止其圖標會出現一個大而可見脈衝效果\""
L["Time Color"] = "計時顏色"
L["Time Font"] = "計時字型"
L["Timer Bar Color"] = "計時條顏色"
L["Timer Bar Texture"] = "計時條材質"
L["Timers On Buttons"] = "按鈕上的計時"
L["Tooltips At Buttons"] = "在按鈕上顯示提示"
L["Tooltips At Buttons Desc"] = "在圖騰按鈕的右側顯示提示."

L["Advanced Options"] = "進階設定"
L["Always Visible Desc"] = "圖騰選單總是可見像動作條一樣四處拖動。"
L["Arrangement"] = "排列方式"
L["Basic layout of the four timer buttons, loose lets you move them individually"] = "4個計時按鈕的基本樣式，自由排列讓你單獨移動"
L["box"] = "方格排列"
L["Button Size"] = "按鈕大小"
L["Cast Button Position"] = "施法按鈕位置"
L["Cast Button Position Desc"] = "設定圖騰額外自訂的按鈕位置與旁邊的圖騰計時"
L["Cast Button Size"] = "施法按鈕大小"
L["Cast Button Size Desc"] = "設定圖騰額外自訂的按鈕大小與旁邊的圖騰計時關聯大小"
L["Enable Pulse Bar"] = "啟用脈動條"
L["Enables the four totem timer buttons and menus"] = "啟用4個圖騰計時按鈕和選單"
L["horizontal"] = "水平方向"
L["Keybindings desc"] = "如果啟用，如果圖騰選單顯示圖騰按鈕將會有按鍵1-9|n你必須重登設定才會生效。"
L["loose"] = "自由排列"
L["Mini Icons Desc"] = "在標示圖騰分配的計時按鈕右下顯示小圖示來啟動多施法法術和計時按鈕將會施放。"
L["Open On Rightclick"] = "右鍵點擊開啟"
L["Player Range"] = "玩家範圍"
L["Player Range Desc"] = "如果玩家超出範圍在圖騰計時上顯示紅點"
L["Pulse desc"] = "在計時裡面顯示綠色狀態條直到充滿圖騰脈動。"
L["Raid Member Range"] = "團隊成員範圍"
L["Raid Range Tooltip"] = "團隊距離提示"
L["Range Desc"] = "在左下角顯示有多少團隊成員沒有獲得你的圖騰增益"
L["Reverse Key Bindings"] = "反向快捷鍵"
L["Reverse Key Desc"] = "鎖定按鍵9-1而不是1-9|n你必須重登這個設定才會生效。"
L["Rightclick Desc"] = "右鍵開啟圖騰選單而不是經過計時按鈕。 用滑鼠中鍵按鈕可以圖騰解散而不是右鍵點擊。"
L["RR Tooltip Desc"] = "滑鼠經過時顯示團隊成員清單沒有在你圖騰範圍內"
L["Scales the timer buttons"] = "縮放圖騰按鈕"
L["Scaling"] = "縮放"
L["Sets the font size of time strings"] = "設定計時字串的字型大小"
L["Sets the format in which times are displayed"] = "設定計時顯示格式"
L["Sets the space between timer buttons"] = "設定計時按鈕之間的間隔"
L["Sets the space between timer buttons and timer bars"] = "設定計時按鈕跟計時條之間的間隔"
L["Sets the width of timer bars."] = "設定計時條的寬度"
L["Show Mini Icons"] = "顯示小圖示"
L["Show Totem Cooldowns"] = "顯示圖騰冷卻"
L["Spacing"] = "間隔"
L["Timer Bar Position"] = "計時條位置"
L["Timer Bar Position Desc"] = "設定在哪一方的圖示計時器顯示的時間"
L["Timer Bar Width"] = "計時條寬度"
L["Timer Bar Width Desc"] = "設定計時條寬度。"
L["Timer Button 1"] = "計時按鈕1"
L["Timer Button 2"] = "計時按鈕2"
L["Timer Button 3"] = "計時按鈕3"
L["Timer Button 4"] = "計時按鈕4"
L["Timers"] = "計時"
L["Timers On Buttons Desc"] = "計時顯示在按鈕上而不是在他們旁邊。如果啟用，武器追蹤只會顯示時間當雙持時只有主手武器。"
L["Time Size"] = "計時大小"
L["Time Spacing"] = "計計時隔"
L["Time Style"] = "計時格式"
L["Totem Cooldowns desc"] = "所有圖騰顯示冷卻就像額外的計時條不再冷卻。"
L["Totem menu direction"] = "圖騰選單方向"
L["Totem menu direction desc"] = "設定圖騰選單開啟方向。 自動確定方向基於計時的位置。"
L["Totem Menu Key Bindings"] = "圖騰選單快捷鍵"
L["Totem Menus Always Visible"] = "圖騰選單總是可見"
L["Totem Menu Spacing"] = "圖騰選單間隔"
L["Totem Menu Spacing Desc"] = "在圖騰選單設定按鈕間隔。只允許如果選單總是可見。"

L["Ankh Tracker"] = "復生追蹤"
L["Ankh Tracker Desc"] = "顯示你復生能力剩餘冷卻時間以及在你背包的復生數目。也被用來儲存或是載入圖騰設定。"
L["Button 4"] = "按鈕4"
L["EarthShieldDesc"] = "顯示大地之盾剩餘時間和次數。 可用於投大地之盾。"
L["EarthShieldOptionsDesc"] = "如果為了滑鼠按鈕'改寫'像設定一樣被選擇，當離開戰鬥盾被施放在最後一人或是被團隊圖騰插件分配。預設用法:離開戰鬥指向你大地之盾目標之後用右鍵點擊按鈕施放法術。那麼你可以指向任何一人，然而用右鍵點擊大地之盾仍然會施放在相同的人身上，甚至在戰鬥中。"
L["Earth Shield Tracker"] = "大地之盾追蹤"
L["ES Charges only"] = "只有消耗"
L["ES Charges only desc"] = "停用時間顯示,在其位置上顯示大地之盾的層數|n 在你下一次施放大地之盾時生效"
L["ES Main Tank Desc"] = "滑鼠停留時顯示了一個選單，裡面最多包含 4個你隊伍/團隊中的主坦克。"
L["ES Main Tank menu"] = "主坦選單"
L["esrecast"] = "改寫 (最後目標/團隊圖騰)"
L["Leftclick"] = "左鍵點擊"
L["Middle Button"] = "中鍵按鈕"
L["Rightclick"] = "右鍵點擊"
L["Shield Tracker"] = "盾追蹤"
L["Trackers"] = "追蹤"
L["Weapon Buff Tracker"] = "武器增益追蹤"
L["WeaponDesc"] = "顯示武器剩餘增益時間。左鍵點擊施放選擇的武器增益，右鍵點擊開啟選單選擇增益。一個圖示顯示兩個增益，第一個左鍵點擊施放左邊增益和第二個左鍵點擊右邊增益。"

L["Color"] = "顏色"
L["disabled warnings desc"] = "即使追蹤禁用，到期增益警告還是會顯示"
L["EarthShield warnings"] = "大地之盾警告"
L["Maelstrom notification"] = "氣漩通知"
L["Messages"] = "訊息"
L["Shield expiration warnings"] = "盾到期警告"
L["Show warnings of disabled trackers"] = "禁用追蹤顯示警告"
L["Sound"] = "聲音"
L["Totem Desctruction Desc"] = "警告如果圖騰在到期前被銷毀。"
L["Totem Destruction Message"] = "圖騰銷毀訊息"
L["Totem Expiration Desc"] = "圖騰到期之後警告。"
L["Totem Expiration Message"] = "圖騰到期訊息"
L["Totem Expiration Warning"] = "圖騰到期警告"
L["Totem Warning Desc"] = "在圖騰10秒到期前警告。"
L["Warnings"] = "警報"
L["Weapon buff warnings"] = "武器增益警告"

L["Cooldowns"] = "冷卻"
L["Duration"] = "期間"
L["ECD Button Size"] = "增強冷卻按鈕大小"
L["ECD Font Size"] = "增強冷卻字型大小"
L["EnhanceCDs"] = "增強冷卻設定"
L["Flame Shock on top"] = "烈焰震擊在頂部"
L["Flame Shock on top desc"] = "顯示烈焰震擊時間與氣旋武器條在冷卻計時器上方"
L["Hide OOC Desc"] = "改變這個設定下一次戰鬥才會生效"
L["Hide out of combat"] = "離開戰鬥隱藏"
L["Lava Surge Aura"] = "熔岩奔騰光環"
L["Lava Surge Aura Desc"] = "如果使用魔獸世界內置的熔岩奔騰特效PowerAuras，則顯示了一個光環圍繞你的角色。"
L["Lava Surge Glow"] = "熔岩奔騰輝光"
L["Lava Surge Glow Desc"] = "當熔岩奔騰特效發動時，讓熔岩爆發的冷卻時間計時器和動作列按鈕發出熔岩爆發的輝光。"
L["Long Cooldowns"] = "長時冷卻"
L["Maelstrom Bar Height"] = "氣漩條高度"
L["OOC Alpha"] = "離開戰鬥透明度"
L["OOC Alpha Desc"] = "離開戰鬥控制不透明的按鈕，0 = 透明, 1 = 不透明"
L["Show OmniCC counters"] = "顯示OmniCC計數"
L["Spells"] = "法術"

L["Arena"] = "競技場"
L["Battleground"] = "戰場"
L["Copy All"] = "複製所有"
L["Copy CC Settings"] = "複製控場設定"
L["Copy EnhanceCDs Settings"] = "複製增強冷卻設定"
L["Copy Frame Positions"] = "複製框架位置"
L["Copy From"] = "複製從"
L["Copy General Settings"] = "複製一般設定"
L["Copy Settings"] = "複製設定"
L["Copy To"] = "複製到"
L["Copy Totem Settings"] = "複製圖騰設定"
L["Copy Totem Timer Settings"] = "複製圖騰計時器設定"
L["Copy Tracker Settings"] = "複製追蹤設定"
L["Copy Warnings"] = "複製警告"
L["Create Profile"] = "創建設定檔"
L["default"] = "預設"
L["Delete Profile"] = "刪除設定檔"
L["Manage Profiles"] = "管理設定檔"
L["New Name"] = "新名稱"
L["Party"] = "隊伍"
L["Profile"] = "設定檔"
L["Profile already exists."] = "設定檔已經存在"
L["Profiles"] = "設定檔"
L["Raid"] = "團隊"
L["Really delete profile?"] = "確定刪除設定檔？"
L["Really reset frame positions?"] = "確定重置框架位置？"
L["Reset Frame Positions"] = "重置框架位置"
L["Reset Profile"] = "重置設定檔"
L["Select Profiles"] = "選擇設定檔"
L["Solo"] = "單獨"
L["You cannot delete the default profile."] = "你無法刪除預設的設定檔."
L["You need to enter a profile name first."] = "你需要先輸入一個設定檔名稱."

    end